### ISSUE TITLE
sentry

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#100]
Let's add sentry for error tracking.

**Comment by yegor256** [comment]
@rultor release, tag is `0.19`

**Comment by yegor256** [comment]
@rultor release, tag is `0.19`

**Comment by yegor256** [comment]
@rultor release, tag is `0.19`

**Comment by yegor256** [comment]
@rultor release, tag is `0.19`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#100` was not in scope
