### ISSUE TITLE
0pdd can't parse gif

### ISSUE THREAD

**Issue by nikialeksey** [yegor256/0pdd#102]
[Sample](https://github.com/nikialeksey/FullScreenDialog/commit/577cf1695ffecf89d928b30b0368b7abb0da3ccf#commitcomment-23338042)

Is it bug? May be there is some configuration with file exclusion strategy?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@nikialeksey do you want it to go into the GIF file and find `@todo` puzzle there? Or you want that file just to be ignored?

**Comment by nikialeksey** [comment]
@yegor256 Of course, want to be ignored))) it's not a text, I don't edit it by myself)

**Comment by nikialeksey** [comment]
Thanks! But, is this a normal that 0pdd make comment for me, because he could not parse the gif? I think, 0pdd should skip files he cant parse

**Comment by yegor256** [comment]
@nikialeksey no, it doesn't skip them. It "fails fast" expecting you to have everything in order, or broken. Nothing in the middle.

**Comment by nikialeksey** [comment]
Got it! Thanks

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#102` was not in scope
