### ISSUE TITLE
Parent issue link

### ISSUE THREAD

**Issue by g4s8** [yegor256/0pdd#103]
It will be handy if PDD bot puts a link to parent task in puzzle issue comment.

E.g. if I create a puzzle:
```
/**
 * @todo #1:30min Add more unit tests.
 */
```
I want to see a link to `#1` issue in a new puzzle.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/0pdd/issues/103#issuecomment-320448937))

@yegor256 Job `gh:yegor256/0pdd#103` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @g4s8, total is [+630](http://www.0crat.com/u/g4s8).

**Comment by yegor256** [comment]
@rultor release, tag is `0.20`

**Comment by g4s8** [comment]
@yegor256 thanks, it's working

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#103` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+1170](http://www.0crat.com/u/yegor256).
