### ISSUE TITLE
security concerns

### ISSUE THREAD

**Issue by caarlos0** [yegor256/0pdd#104]
0pdd.com shows recent projects in its home page, including private repos.

Any "attacker" can see them, and, knowing a repo exists and is managed by 0pdd, the "attacker" can see the tasks of a repo he doesn't have access to by accessing `0pdd.com/p?name=owner/repo`.

We should probably hide private repos on the home page and add login + permission checks to the `/p` endpoint.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/0pdd/issues/104#issuecomment-320455583))

@yegor256 Job `gh:yegor256/0pdd#104` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @caarlos0, total is [+180](http://www.0crat.com/u/caarlos0).

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.5`

**Comment by yegor256** [comment]
@caarlos0 I believe it's fixed now, private repos won't be visible on the front page. Thanks for reporting this!

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#104` assigned to @tedtoer, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#104` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @tedtoer, total is [+30](http://www.0crat.com/u/tedtoer).
