### ISSUE TITLE
Tag already exists, won't submit again (false positive)

### ISSUE THREAD

**Issue by fxnn** [yegor256/0pdd#106]
0pdd stopped to file issues for new puzzles on my project. Instead, it replies to every commit with the message:

    Tag "2-0082b70e/submit" already exists, won't submit again.

However, I only filed this puzzle once, in exactly one place in the code. Later commits didn't even change the file the tag is in. Also, there are no other `@todo` lines with the marker `#2`.

* [Project at 0pdd.com](http://www.0pdd.com/p?name=fxnn/deadbox)
* [Commit comment for puzzle creation](https://github.com/fxnn/deadbox/commit/dcf925d54d06443edfc1f6c99233012b3ef2adf1#commitcomment-23895009)
* [Commit comment showing this bug the first time](https://github.com/fxnn/deadbox/commit/ab75eb0ff3bd527d7673f626c414315d72baf1c6#commitcomment-23895159)
* [Commit comment showing this bug the second time](https://github.com/fxnn/deadbox/commit/054dba37675bdc9ebbeee451b0d974805863e063#commitcomment-23895354)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by fxnn** [comment]
Oh, this bug could be related to the fact that the [project's 0pdd.com page](http://www.0pdd.com/p?name=fxnn/deadbox) shows `0 alive, 0 total` puzzles and an rather empty [XML file](http://www.0pdd.com/xml?name=fxnn/deadbox)

However, there should be something like 10 puzzles for the project.

**Comment by yegor256** [comment]
@fxnn indeed, the problem is that the XML file is empty, but the log says that all issues were submitted to GitHub: http://www.0pdd.com/p?name=fxnn/deadbox Let me investigate the reason.

**Comment by yegor256** [comment]
@fxnn I tried everything, but wasn't able to reproduce the bug :( Looks like it happens when there many puzzles in one commit. Or maybe after my manipulations, it's just gone. Anyway, please, try to push again to your repo and we'll see.

**Comment by fxnn** [comment]
@yegor256 Okay, I [pushed](https://github.com/fxnn/deadbox/commit/1e066de8873d00e22985c1f466a47932ef8383e1) to the repo and it seems that @0pdd discovered all puzzles now! Also, the [project's page on 0pdd.com](http://www.0pdd.com/p?name=fxnn/deadbox) now correctly displays all puzzles and the XML is non-empty.

@0pdd filed issues that were already there, but I guess that's okay as you deleted the project's log on 0pdd.com. The bot created 10 new issues, so if it was the amount of puzzles, then that's no problem anymore (as the first errorneous commit also contained 10 puzzles).

So, I think the issue is solved. Btw, thank you for providing the 0pdd.com service :)

**Comment by yegor256** [comment]
@fxnn I'm glad this issue is solved, but we have to keep an eye on it. I don't really know what was the problem. Please, close this ticket and don't hesitate to submit new ones if you spot any problem. Thanks for using 0pdd! :)

**Comment by fxnn** [comment]
Be sure that I'll report any issues!

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#106` was not in scope
