### ISSUE TITLE
puzzles.rb:35-38: It's not really effective to always save...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/0pdd#11]
The puzzle `3-09c2d743` in `objects/puzzles.rb` has to be resolved: It's not really effective to always save the XML document back to storage, even when it was not really modified. Would be much better to check whether any modifications have been made and skip that SAVE() operation.. The puzzle was created by Yegor Bugayenko on 13-Dec-16. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by yegor256** [comment]
@vivekimsit can you help with this one?

**Comment by 0pdd** [comment]
The puzzle `3-09c2d743` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#11` was not in scope

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
