### ISSUE TITLE
0pdd.rb:57-59: Let's add DynamoDB Local for the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/0pdd#111]
The puzzle `110-9c9d8a7c` (from #110) in [`0pdd.rb`](https://github.com/yegor256/0pdd/blob/master/0pdd.rb) (lines 57-59) has to be resolved: "Let's add DynamoDB Local for the testing cycle and make sure we work correctly with Dynamo persistence layer. Somehow we must also fix the Rakefile."

The puzzle was created by yegor256 on 14-Sep-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `110-9c9d8a7c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#111` was not in scope

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
