### ISSUE TITLE
0pdd.rb:199-201: Let's not show the MORE link in the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/0pdd#112]
The puzzle `110-1d6b79a2` (from #110) in [`0pdd.rb`](https://github.com/yegor256/0pdd/blob/master/0pdd.rb) (lines 199-201) has to be resolved: "Let's not show the MORE link in the log list if the list doesn't have any more elements. At the moment we keep showing that MORE link if any elements are there."

The puzzle was created by yegor256 on 14-Sep-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#112](https://github.com/yegor256/0pdd/issues/112) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job [#112](https://github.com/yegor256/0pdd/issues/112) is already in scope

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
The job [#112](https://github.com/yegor256/0pdd/issues/112) assigned to @pbenety[/z](https://www.0crat.com/u/pbenety), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1340660568); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@pbenety[/z](https://www.0crat.com/u/pbenety) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `110-1d6b79a2` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by 0crat** [comment]
The job [#112](https://github.com/yegor256/0pdd/issues/112) is now out of scope
