### ISSUE TITLE
Rakefile:28-30: Let's make puzzles.xsd publicly...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/0pdd#113]
The puzzle `110-b6547ac0` (from #110) in [`Rakefile`](https://github.com/yegor256/0pdd/blob/master/Rakefile) (lines 28-30) has to be resolved: "Let's make puzzles.xsd publicly avaiable in the web and let's add it to the XML files we save, so that users can see the XSD schema together with the XML content."

The puzzle was created by yegor256 on 14-Sep-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `110-b6547ac0` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#113`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#113` is not in scope.

**Comment by yegor256** [comment]
@rultor release, tag is `0.25.4`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
