### ISSUE TITLE
0pdd does not close issue

### ISSUE THREAD

**Issue by DronMDF** [yegor256/0pdd#123]
Issue https://github.com/DronMDF/goost/issues/214
Created from puzzle in kuznyechik/Iterator.h

puzzle was removed in this merge commit: https://github.com/DronMDF/goost/commit/7c0d9fd3f8b07b6a576fe00f48e709d9226013cb#comments

Issue sill open.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by irbuch** [comment]
I've investigated this issue . So, probably  the cause of this issue it's  that github was unavailable when #0pdd was trying to update status of the customer`s issue in repo. after committed and merged.
You can check the id of puzzle 103-9cc10377 from the issue in customer`s repo. by the link http://www.0pdd.com/p?name=DronMDF/goost, (just Ctrl + F and past ID in browser ), as you can see id with this sign has marked as closed.

**Comment by DronMDF** [comment]
@irbuch If 0pdd cause problem with update status on github - him should not commit status of Job, I think. 

What should I do with this now? To go and close for 0pdd tickets by hand? Wash the idea in another.

The problem is repeated again and again.
https://github.com/DronMDF/goost/issues/277
https://github.com/DronMDF/goost/issues/286

**Comment by irbuch** [comment]
I agree with you that  0pdd should close issues after puzzle was removed or changed, but I thought that this issue appeared only one.
In case of two issues above, puzzles of them still in your code in master branch:
https://github.com/DronMDF/goost/blob/master/magma/BlockIterator.h#L12

**Comment by DronMDF** [comment]
I comment removed line in merge commits for all issues.

BlockIterator - This is https://github.com/DronMDF/goost/issues/278 and
https://github.com/DronMDF/goost/issues/279
It ticket is open, this is a ok.


Андрей Валяев
Twitter: @Dronmdf
skype: dron_valyaev
G+: google.com/+АндрейВаляев
<http://google.com/+%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B9%D0%92%D0%B0%D0%BB%D1%8F%D0%B5%D0%B2>


2017-10-08 22:17 GMT+03:00 irbuch <notifications@github.com>:

**Comment by yegor256** [comment]
@irbuch I don't think that's the case, because when we fail to update GitHub an exception is thrown and reported to Sentry. I don't have anything in Sentry, no errors, no exceptions. But maybe I'm wrong and exceptions are being swallowed somewhere somehow. What do you suggest to do?

**Comment by yegor256** [comment]
@irbuch please, don't forget to always start your message with the name of the person you're sending it to. Otherwise, I will just miss it. More about it: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments

**Comment by irbuch** [comment]
@yegor256 I can't reproduce this issue in my two test repositories (C++ , RoR). I know that prm. language doesn't matter but I've tried to simulate steps and text environment as  in code example, but without result. I will take some more time and try to investigate more detail.

**Comment by yegor256** [comment]
@irbuch that's the problem - it's very hard to reproduce this issue. I can't understand why it's happening __sometimes__. What we can do is to experiment and try. Try to reproduce in a unit test. Maybe we'll get lucky.

**Comment by yegor256** [comment]
@irbuch @DronMDF I think I know what is the problem. It's here: https://github.com/yegor256/0pdd/blob/0.24.6/objects/puzzles.rb#L68-L70

We're checking all puzzles that are supposed to be closed and call `close()` on GitHub API. We don't record the fact that the issue was actually closed already. Thus, on each commit we're doing a many calls to GitHub API. Sometimes our usage goes over the limit and we simply stop doing anything. We stop closing issues and submitting new ones.

Thus, the solution would be to store the fact that the issue was closed through GitHub API in our XML document. Just like we store the fact that the issue was submitted. Then, we just check for that flag and don't call `close()` on GitHub API so often.

**Comment by irbuch** [comment]
@yegor256 Got it. I will take care about this.

**Comment by yegor256** [comment]
@irbuch also, I think that silently ignoring the fact that we are over the limit with GitHub API is not a good idea. We may have similar problems in the future. We should think about some other mechanism. Maybe we should delay the operation, saving it into some queue, like AWS SQS. But this is for the future.

**Comment by DronMDF** [comment]
@yegor256 At this moment i have 4 solved, but open issue.
https://github.com/DronMDF/goost/issues/214
https://github.com/DronMDF/goost/issues/277
https://github.com/DronMDF/goost/issues/286
https://github.com/DronMDF/goost/issues/290
In some cases, there was a file renaming.

**Comment by DronMDF** [comment]
@yegor256 Is there any progress on this issue?

**Comment by yegor256** [comment]
@DronMDF not yet. Looks like I have to fix it myself.

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#123` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+4315](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#123` is already assigned to @yegor256.

**Comment by DronMDF** [comment]
@yegor256 I have an idea. 
'assign my' should cost -35. assign other - -5.

assign my for -5 is very profit.

**Comment by yegor256** [comment]
@rultor release, tag is `0.25.1`

**Comment by yegor256** [comment]
@DronMDF I believe the issue is fixed. Let's monitor...

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#123` is already assigned to @yegor256.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#123` is already assigned to @yegor256.

**Comment by yegor256** [comment]
@DronMDF I made many changes in #137 Hopefully, they will help. Let's watch.

**Comment by 0crat** [comment]
@yegor256 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@yegor256 resigned from `gh:yegor256/0pdd#123`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#123` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#123` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#123` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#123` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#123` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#123` is not assigned to anyone.

**Comment by yegor256** [comment]
@DronMDF I think we can close this ticket? Or you still see the problem?

**Comment by DronMDF** [comment]
@yegor256 This is fixed, IMO.

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#123` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @tedtoer, total is [+90](http://www.0crat.com/u/tedtoer).
