### ISSUE TITLE
Cannot rebase: You have unstaged changes.

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#125]
```
set -x;set -e;set -o pipefail;cd /tmp/0pdd20171001-4-w2x441/yegor256/pdd && git reset --hard --quiet && git clean --force -d && git fetch --quiet && git checkout master && git rebase --abort || true && git rebase --strategy-option=theirs origin/master: pid 19219 exit 1 (not zero):
+ set -e
+ set -o pipefail
+ cd /tmp/0pdd20171001-4-w2x441/yegor256/pdd
+ git reset --hard --quiet
+ git clean --force -d
+ git fetch --quiet
+ git checkout master
Already on 'master'
+ git rebase --abort
No rebase in progress?
+ true
+ git rebase --strategy-option=theirs origin/master
Cannot rebase: You have unstaged changes.
Please commit or stash them.

M	test_assets/aladdin.jpg
M	test_assets/article.pdf
M	test_assets/cambria.woff
M	test_assets/elegant-objects.png
M	test_assets/favicon.ico
Your branch is behind 'origin/master' by 14 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

/app/objects/exec.rb:41:in `block in run'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:205:in `popen_run'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/open3.rb:95:in `popen3'
/app/objects/exec.rb:39:in `run'
/app/objects/git_repo.rb:100:in `pull'
/app/objects/git_repo.rb:67:in `push'
/app/objects/job.rb:39:in `proceed'
/app/objects/job_starred.rb:33:in `proceed'
/app/objects/job_recorded.rb:32:in `proceed'
/app/objects/job_emailed.rb:34:in `proceed'
/app/objects/job_commiterrors.rb:34:in `proceed'
/app/objects/job_detached.rb:49:in `block in exclusive'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/app/objects/job_detached.rb:47:in `exclusive'
/app/objects/job_detached.rb:37:in `block in proceed'
/app/objects/job_detached.rb:37:in `fork'
/app/objects/job_detached.rb:37:in `proceed'
/app/0pdd.rb:336:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `block in compile!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (3 levels) in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1010:in `route_eval'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (2 levels) in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1037:in `block in process_route'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `process_route'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:989:in `block in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1094:in `block in dispatch!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1091:in `dispatch!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/path_traversal.rb:16:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/logger.rb:15:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:231:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:224:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:194:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1955:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1726:in `synchronize'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.6`

**Comment by yegor256** [comment]
It happens only sometimes. For example:

  * Happened here: https://github.com/yegor256/pdd/commit/732ea9f2fc4bfd8cbdc1a2c9e59513606586bf2d#comments
  * Didn't happen here: https://github.com/yegor256/pdd/commit/b840dc0d0a5a88d7e4cd8980df0c7464baec9f83

**Comment by yegor256** [comment]
@irbuch can you try to fix this too?

**Comment by 0crat** [comment]
Job [#125](https://github.com/yegor256/0pdd/issues/125) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8435](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#125](https://github.com/yegor256/0pdd/issues/125) assigned to @dmydlarz[/z](https://www.0crat.com/u/dmydlarz), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1301164036); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
The job [#125](https://github.com/yegor256/0pdd/issues/125) assigned to @danielpalafox[/z](https://www.0crat.com/u/danielpalafox), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1790857422); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@danielpalafox[/z](https://www.0crat.com/u/danielpalafox) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The job [#125](https://github.com/yegor256/0pdd/issues/125) assigned to @mesut[/z](https://www.0crat.com/u/mesut), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1871148210); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by mesut** [comment]
@0crat wait for #226

**Comment by 0crat** [comment]
> @0crat wait for PR #226  ([here](https://github.com/yegor256/0pdd/issues/125#issuecomment-404124652))

@mesut The impediment for [#125](https://github.com/yegor256/0pdd/issues/125) was registered successfully by @mesut[/z](https://www.0crat.com/u/mesut)

**Comment by yegor256** [comment]
@mesut thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @mesut[/z](https://www.0crat.com/u/mesut)

**Comment by 0crat** [comment]
The job [#125](https://github.com/yegor256/0pdd/issues/125) is now out of scope

**Comment by 20GHhub19** [comment]
Hello dear all

I start learning with git:

I typed this command in a git console : git fetch because I wanted to update index
 and I got this error message: error: cannot rebase: You have unstaged changes.
                                              error: Please commit or stash them.

find in attached file a screenshot I did I don't how to resolve it
![Git_fetch_error](https://user-images.githubusercontent.com/58400969/102632992-20e50080-4150-11eb-8121-d6a39caf21e1.jpg)

**Comment by 20GHhub19** [comment]
Hello dear all

I start learning with git:

I typed this command in a git console : git fetch because I wanted to update index
and I got this error message: error: cannot rebase: You have unstaged changes.
error: Please commit or stash them.

find in attached file a screenshot I did I don't how to resolve it
![Git_fetch_error_2](https://user-images.githubusercontent.com/58400969/102633540-dca63000-4150-11eb-8ed0-5a49238e9194.jpg)
