### ISSUE TITLE
Setup local development copy of 0pdd

### ISSUE THREAD

**Issue by tommasop** [yegor256/0pdd#126]
I was trying to setup the 0pdd project locally.

When I do a rackup it complains about a [config.yml](https://github.com/yegor256/0pdd/blob/224420cfbf43cba6f3269c00cbd5b8ebae2f82d6/deploy.sh#L8) missing.

Is there any config.yml example to be added to the repository to guide in development setup?

Thanks

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@tommasop what exactly do you do? How can I reproduce the problem?

**Comment by tommasop** [comment]
I found out what I needed thanks

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#126` was not in scope

**Comment by kalloc** [comment]
@yegor256 
I would like to run private copy of 0pdd web service, I need working configuration.
I don't found  `config.yml` in repo.
It helps if you show me an example, i can read source, but it will spend more time.

thanks

**Comment by yegor256** [comment]
@kalloc see 494bc19 Does it help?

**Comment by kalloc** [comment]
@yegor256 yeap, thanks
