### ISSUE TITLE
Octokit::InvalidRepository: Invalid Repository. Use user/repo format.

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#127]
https://sentry.io/zerocracy/0pdd/issues/361893877/

```
Octokit::InvalidRepository: Invalid Repository. Use user/repo format.
  octokit/repository.rb:90:in `raise_invalid_repository!'
    raise Octokit::InvalidRepository, "Invalid Repository. Use user/repo format."
  octokit/repository.rb:34:in `initialize'
    raise_invalid_repository!
  octokit/repository.rb:58:in `new'
    new(repo).path
  octokit/repository.rb:58:in `path'
    new(repo).path
  octokit/client/repositories.rb:29:in `repository'
    get Repository.path(repo), options
...
(45 additional frame(s) were not displayed)

Octokit::InvalidRepository: Invalid Repository. Use user/repo format.
```

Full stack trace:

```
Octokit::InvalidRepository: Invalid Repository. Use user/repo format.
  from octokit/repository.rb:90:in `raise_invalid_repository!'
  from octokit/repository.rb:34:in `initialize'
  from octokit/repository.rb:58:in `new'
  from octokit/repository.rb:58:in `path'
  from octokit/client/repositories.rb:29:in `repository'
  from 0pdd.rb:388:in `repo'
  from 0pdd.rb:208:in `block in <top (required)>'
  from sinatra/base.rb:1632:in `call'
  from sinatra/base.rb:1632:in `block in compile!'
  from sinatra/base.rb:991:in `block (3 levels) in route!'
  from sinatra/base.rb:1010:in `route_eval'
  from sinatra/base.rb:991:in `block (2 levels) in route!'
  from sinatra/base.rb:1037:in `block in process_route'
  from sinatra/base.rb:1035:in `catch'
  from sinatra/base.rb:1035:in `process_route'
  from sinatra/base.rb:989:in `block in route!'
  from sinatra/base.rb:988:in `each'
  from sinatra/base.rb:988:in `route!'
  from sinatra/base.rb:1094:in `block in dispatch!'
  from sinatra/base.rb:1073:in `block in invoke'
  from sinatra/base.rb:1073:in `catch'
  from sinatra/base.rb:1073:in `invoke'
  from sinatra/base.rb:1091:in `dispatch!'
  from sinatra/base.rb:923:in `block in call!'
  from sinatra/base.rb:1073:in `block in invoke'
  from sinatra/base.rb:1073:in `catch'
  from sinatra/base.rb:1073:in `invoke'
  from sinatra/base.rb:923:in `call!'
  from sinatra/base.rb:913:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:26:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/common_logger.rb:33:in `call'
  from sinatra/base.rb:231:in `call'
  from sinatra/base.rb:224:in `call'
  from rack/head.rb:12:in `call'
  from rack/method_override.rb:22:in `call'
  from sinatra/base.rb:194:in `call'
  from sinatra/base.rb:1955:in `call'
  from sinatra/base.rb:1499:in `block in call'
  from sinatra/base.rb:1726:in `synchronize'
  from sinatra/base.rb:1499:in `call'
  from rack/handler/webrick.rb:86:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:296:in `block in start_thread'
```

**Comment by yegor256** [comment]
@irbuch can you take care of this one? It seems to be not so complex and can be solved in one pull request (I hope).

**Comment by yegor256** [comment]
@0crat assign @irbuch

**Comment by 0crat** [comment]
> @0crat assign @irbuch ([here](https://github.com/yegor256/0pdd/issues/127#issuecomment-335040295))

@yegor256 Job `gh:yegor256/0pdd#127` assigned to @irbuch, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)). @irbuch is not a member of this project yet, but can request to join. @irbuch check your [Zerocracy profile](http://www.0crat.com/u/irbuch) and follow the instructions.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+3725](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@0crat assign @tedtoer

**Comment by 0crat** [comment]
> @0crat assign @tedtoer ([here](https://github.com/yegor256/0pdd/issues/127#issuecomment-336090935))

@yegor256 Job `gh:yegor256/0pdd#127` assigned to @tedtoer, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)). @tedtoer is not a member of this project yet, but can request to join. @tedtoer check your [Zerocracy profile](http://www.0crat.com/u/tedtoer) and follow the instructions.

**Comment by tedtoer** [comment]
@yegor256 how can I take an access to https://sentry.io/zerocracy/0pdd/issues/361893877/ ?
I just logged at http://www.0crat.com/ through my github profile

**Comment by yegor256** [comment]
@tedtoer you should have Sentry access now

**Comment by tedtoer** [comment]
@yegor256 when I go https://sentry.io/zerocracy/0pdd/issues/361893877/ i get "The project you were looking for was not found.", but I have access to Zerocracy organization
I think its because access rights settings

**Comment by yegor256** [comment]
@tedtoer here is the project you need: https://sentry.io/zerocracy/0pdd-j0/

**Comment by tedtoer** [comment]
@yegor256 yes, I saw it, but there are not issues in this project

**Comment by yegor256** [comment]
@tedtoer they will be there once we deploy the new version, wait for it.

**Comment by tedtoer** [comment]
@yegor256 ah, ok. Please mention me here when you deployed

**Comment by yegor256** [comment]
@tedtoer version 0.25 is in production, you should see exceptions in Sentry

**Comment by yegor256** [comment]
@tedtoer I believe this problem is fixed already.

**Comment by 0crat** [comment]
Oops! There is an open order for this job, @tedtoer is still working with it.

**Comment by 0crat** [comment]
@tedtoer this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@tedtoer resigned from `gh:yegor256/0pdd#127`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#127` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#127` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#127` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#127` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#127` is not assigned to anyone.
