### ISSUE TITLE
JobEmailed should CC repository owner

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#129]
Let's improve `JobEmailed` so that it CC the owner of the repo, if his email is available in GitHub repo. In some cases it will work and emails will be sent.

**Comment by yegor256** [comment]
@0crat assign @irbuch

**Comment by 0crat** [comment]
> @0crat assign @irbuch ([here](https://github.com/yegor256/0pdd/issues/129#issuecomment-335150341))

@yegor256 Job `gh:yegor256/0pdd#129` assigned to @irbuch, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)). @irbuch is not a member of this project yet, but can request to join. @irbuch check your [Zerocracy profile](http://www.0crat.com/u/irbuch) and follow the instructions.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+3755](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/0pdd/issues/129#issuecomment-335229343))

@yegor256 @irbuch resigned from `gh:yegor256/0pdd#129`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#129` assigned to @tedtoer, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by tedtoer** [comment]
@yegor256 what is "CC" in this case?

**Comment by tedtoer** [comment]
@yegor256 Is "CC" a "closed copy"?

**Comment by tedtoer** [comment]
@yegor256 I sent PR, please check out

**Comment by 0crat** [comment]
Oops! There is an open order for this job, @tedtoer is still working with it.

**Comment by yegor256** [comment]
@rultor release, tag is `0.25`

**Comment by yegor256** [comment]
@tedtoer thanks a lot!

**Comment by 0crat** [comment]
@tedtoer this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@tedtoer resigned from `gh:yegor256/0pdd#129`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#129` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#129` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#129` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#129` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#129` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#129` is not assigned to anyone.
