### ISSUE TITLE
Check repository and archives of releases on some leak of credentials. 

### ISSUE THREAD

**Issue by irbuch** [yegor256/0pdd#130]
Need to find and remove potential  vulnerabilities of personal data, such as password or keys, from some config files which can remained  in code-base.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.7`

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.7`

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#130` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#130` is already assigned to @yegor256, sorry.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+3790](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@irbuch I believe it's fixed, all keys were revoked. Many thanks for reporting this!

**Comment by yegor256** [comment]
@irbuch please, close this ticket if the problem was solved. Thanks.

**Comment by irbuch** [comment]
If credentials in releases 24.5 and lower was revoked,  I will close issue, but config.yml still there.

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#130` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+3820](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@irbuch it's OK, the file will stay there, but all credentials are expired, no harm will be done. Thanks again for your help.
