### ISSUE TITLE
How to clear duplicate puzzles ?

### ISSUE THREAD

**Issue by irbuch** [yegor256/0pdd#136]
My issues in list are closed, but during creation a of a new puzzle I'm  getting error:
```bash
/home/user/Documents/projects/0pdd/objects/exec.rb:41:in `block in run': set -x;set -e;set -o pipefail;cd /tmp/0pdd20171024-13963-3eav1n/user/codequiz-master && pdd -q -f /tmp/pdd.xml20171024-14375-18icy83: pid 14403 exit 255 (not zero): (RuntimeError)
+ set -e
+ set -o pipefail
+ cd /tmp/0pdd20171024-13963-3eav1n/irbuch/codequiz-master
+ pdd -q -f /tmp/pdd.xml20171024-14375-18icy83

ERROR: there are 2 duplicate(s) of the same puzzle: app/jobs/application_job.rb:2-2, app/models/account.rb:2-2, while maximum 1 duplicate is allowed
```
even if I remove puzzles in ```tmp```  folder, the  issue still reproduce.
 In  post-parsing rules I've specified: 
```--rule=max-duplicates:3```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@irbuch `--rule=max-duplicates:` doesn't work. You may have only one puzzle per project. Just make sure they are all unique and never have the same text.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#136`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#136` is not in scope.
