### ISSUE TITLE
github_tickets.rb:36-39: This mechanism of body abbreviation is r...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/0pdd#14]
The puzzle `3-9fa46796` in `objects/github_tickets.rb` (lines 36-39) has to be resolved: This mechanism of body abbreviation is rather primitive and doesn't produce readable texts very often. Instead of cutting the text at the hard limit (40 chars) we have to cut it at the end of the word, staying closer to the limit..

The puzzle was created by Yegor Bugayenko on 13-Dec-16. 

Estimate: 20 minutes, Role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by yegor256** [comment]
@vivekimsit can you help with this?

**Comment by vivekimsit** [comment]
@yegor256 sure I will look into it.

**Comment by yegor256** [comment]
@vivekimsit thanks! let me know if any problems

**Comment by vivekimsit** [comment]
@yegor256 sure, today I will try to get through the source code and then would think of some better solution.

**Comment by vivekimsit** [comment]
@yegor256 I did some tinkering and wrote an algorithm which I think works fine. You can check the link:

https://repl.it/FFLW/3

wdyt?

**Comment by yegor256** [comment]
@vivekimsit looks good, please submit a pull request

**Comment by yegor256** [comment]
@vivekimsit what is the status of this one?

**Comment by vivekimsit** [comment]
@yegor256 I thinks its already merged #43

**Comment by 0pdd** [comment]
The puzzle `3-9fa46796` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#14` was not in scope

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
