### ISSUE TITLE
Tag "9-5878affc/closed" already exists, won't close again. 

### ISSUE THREAD

**Issue by extsoft** [yegor256/0pdd#144]
Please take a look for [this message](https://github.com/extsoft/elegant-git/commit/4f1b3d85cc6f7fec9e7fa3479b454d9ed87e951a#commitcomment-25533431). New puzzles can be created. 

The same for the next commit - https://github.com/extsoft/elegant-git/commit/9d083db472673043a31cb6f594dfd6654a2db6f8#commitcomment-25565935

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@extsoft I fixed it, please try again. If you see this bug again, please report.

**Comment by yegor256** [comment]
@extsoft works fine?

**Comment by extsoft** [comment]
@yegor256 Sorry for the long reply. Yes, it works.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#144`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#144` is not in scope.
