### ISSUE TITLE
Document how it works with branches

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#146]
Quote from [the article](http://www.yegor256.com/2017/04/05/pdd-in-action.html):

> Every time you git push something new, it does a git pull and retrieves your changes from GitHub. Then it runs pdd, a command line tool that scans the entire code base and finds all occurrences of @todo markers.

Does it mean that it will react on any pushes on any branches? How to avoid tickets creation when I'm pushing to temporary (working) branch? I'd like to limit 0pdd to create the issues only when I'm pushing to the master branch. How I can do that?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@php-coder this is how it works, only with the `master` branch (actually, the default one). All other branches are ignored, see: https://github.com/yegor256/0pdd/blob/0.25.8/0pdd.rb#L406

**Comment by php-coder** [comment]
@yegor256 Thanks!

> settings.github.repository(name)['default_branch']

Is this setting came from a config file and can be configured by user?

**Comment by yegor256** [comment]
@php-coder we're getting this information from your GitHub repository, see: https://help.github.com/articles/setting-the-default-branch/

**Comment by lastk** [comment]
@yegor256 can you close this issue ?

**Comment by yegor256** [comment]
@lastk closed

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#146` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
