### ISSUE TITLE
Make issue subject configurable

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#147]
0pdd uses hard-coded and undocumented format for issues' subject. I'd like to change it to exclude filename and lines and leave only a comment.

In particular, I'm trying to resolve the following:

<img width="642" alt="2017-12-02 0 55 31" src="https://user-images.githubusercontent.com/87088/33508676-09ad4f74-d6fc-11e7-849a-0d33defbb7db.png">

Also, I'd like to know why there are only `...`? I expected to see there my comments.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@php-coder sounds like a good idea, let me implement it

**Comment by yegor256** [comment]
@rultor release, tag is `0.26`

**Comment by yegor256** [comment]
@php-coder I guess it works now, please try (see the updated README in 2893ec9)

**Comment by php-coder** [comment]
Thanks!

**Comment by php-coder** [comment]
When I tried to use it, it didn't work: https://github.com/yegor256/0pdd/issues/154

**Comment by yegor256** [comment]
@php-coder I believe it's fixed, right?

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#147`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#147` is not in scope.
