### ISSUE TITLE
Make issue body configurable

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#148]
If would be very handy to be able to customize issue's body.

For example, user could solve https://github.com/yegor256/0pdd/issues/70 on his own. Also it will become possible to use custom formatting.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@php-coder I don't like the idea of making it entirely configurable, but we definitely can make certain parts "skippable". What would you like to skip? What formatting options would you like to see?

**Comment by php-coder** [comment]
At least I need the following:
- stable links (https://github.com/yegor256/0pdd/issues/149)
- optional estimate/role (https://github.com/yegor256/0pdd/issues/70)
- custom messages that is added to a subject (that supports inserting dynamic values, like commit hash, issue, author). At this time, I have to manually edit each issue after it's creation

Additionally I'd like to see a snippet with the code where this todo marker is added (probably, with 3-5 lines after the comment.

Thanks!

**Comment by yegor256** [comment]
@php-coder I believe most of the problems are fixed here. Let's close this ticket and open a new one, per each issue you're still having

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#148`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#148` is not in scope.
