### ISSUE TITLE
Issue body: use stable links

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#149]
The links to the master branch could quickly became inaccessible if file is renamed/modified. It's better to use stable links (with commit hash in path). In this case, GitHub even will be able to embed a related lines of code to the issue.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.27.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.27.5`

**Comment by yegor256** [comment]
@php-coder I believe it's fixed

**Comment by php-coder** [comment]
@yegor256 WDYT about adding also lines: https://github.com/yegor256/0pdd/commit/a0f20ffaaba42852ac09ac158e2b14d4590a0074#r26042908 ?

**Comment by yegor256** [comment]
@rultor release, tag is `0.27.6`

**Comment by yegor256** [comment]
@rultor release, tag is `0.27.7`

**Comment by yegor256** [comment]
@php-coder I believe it works now, many thanks for the hint!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#149`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#149` is not in scope.
