### ISSUE TITLE
job.rb:34-37: We may lose the moment of update and for...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/0pdd#15]
The puzzle `13-4c2685d4` in `objects/job.rb` (lines 34-37) has to be resolved: We may lose the moment of update and forget to create an issue or close it. For many reasons that may happen. No matter why, we have to do the second check once in a while and update GitHub issues. Maybe every hour or so.

The puzzle was created by Yegor Bugayenko on 13-Dec-16. 

Estimate: 30 minutes, Role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#15`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#15` is not in scope.

**Comment by 0pdd** [comment]
The puzzle `13-4c2685d4` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#15`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#15` is not in scope.

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
