### ISSUE TITLE
Document whether it's safe to modify generated issues

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#150]
I don't properly understand all the details and I have many question on what I can do and what I can't. In particular, I'm scare that all the issues will be closed after my actions. This point can be clarified in documentation.

It is safe to modify issues' titles?
It is safe to modify issues' bodies?
What will happen if I close one of such issues manually? I hope that it won't be reopened or a new one generated.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@php-coder how about 19d1daa ?

**Comment by php-coder** [comment]
@yegor256 LGTM (and also see my comment).

**Comment by yegor256** [comment]
@php-coder thanks, fixed

**Comment by php-coder** [comment]
Thanks!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#150`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#150` is not in scope.
