### ISSUE TITLE
Issue title: compact format for single-line todo

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#151]
Issue's title `ImportSeriesForm.java:83-83: ...` could be simplified to `ImportSeriesForm.java:83: ...`

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.27.4`

**Comment by yegor256** [comment]
@php-coder I believe it's fixed in 0.27.4 Thanks for the hint!

**Comment by yegor256** [comment]
@php-coder please, check and close the ticket

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#151`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#151` is not in scope.
