### ISSUE TITLE
.coveralls.yml: do we really need it if we use codecov.io now?

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#153]
As far I can see we're using codecov.io for code coverage. Is the `.coveralls.yml` file is used? Also I see that it contains repo token, I hope that it's not something that should be kept secret.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@php-coder you're right, it's garbage, deleted in f1fb363

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#153`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#153` is not in scope.
