### ISSUE TITLE
Fails to create an issue: 422 - Invalid request: No subschema in "anyOf" matched

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#154]
See an error here: https://github.com/php-coder/mystamps/commit/2da5416037b0c80c1f0689a4ea31a1185f0b60d9#commitcomment-26016070

Could be related to recently introduced "short-title" feature: https://github.com/yegor256/0pdd/issues/147

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by php-coder** [comment]
I confirm that it relates to "short-title" feature.

**Comment by yegor256** [comment]
@rultor release, tag is `0.27.9`

**Comment by yegor256** [comment]
@php-coder I believe it's fixed, please check
