### ISSUE TITLE
Document a behavior: comment and puzzle is being created from the latest commit

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#155]
It could be a bit unexpected when you see it first time, but puzzle could be created on a commit that actually doesn't add puzzle at all.

For example, if you have 2 commits where the first is adding puzzle, but you are pushing them together. In this case, comment will be added to the 2nd commit.

The same could happen when 0pdd fails due to a parsing bug and later  you push another commit that fixes (or working around) this bug.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@php-coder see 41eb565 Would that be enough?

**Comment by php-coder** [comment]
If it's possible I'd like to see something like "known issues" section in the documentation.

**Comment by yegor256** [comment]
@php-coder how about now: 9c0e9dd ?

**Comment by php-coder** [comment]
@yegor256 LGTM. Thanks!

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#155` is not in scope.
