### ISSUE TITLE
Improve handling of the empty list of collaborators

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#159]
See example: https://github.com/php-coder/mystamps/issues/745#issuecomment-349123749

We shouldn't show a list if it's empty. Moreover, if bot doesn't have permissions, most likely this list always will be empty.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@php-coder it's something else, fixed in 0883b86

**Comment by yegor256** [comment]
@rultor release, tag is `0.27.8`

**Comment by yegor256** [comment]
@php-coder I believe it's fixed, please check

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#159`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#159` is not in scope.
