### ISSUE TITLE
Make length of the issue's title configurable

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#163]
I'd like to be able to configure length of the issue's title. 60 characters isn't enough to me.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.28`

**Comment by yegor256** [comment]
@php-coder it's implemented, see the README

**Comment by php-coder** [comment]
@yegor256 Thanks!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#163`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#163` is not in scope.
