### ISSUE TITLE
Strip a path to the temporary root directory from the error message

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#165]
The full path to the file makes sense for pdd but it's useless to me when it's being reported by 0pdd because the root directory is a temporary directory:
```
+ pdd -q -f /tmp/pdd.xml20171208-4654-1rlfg4o

ERROR: /tmp/0pdd20171208-4-je7stx/php-coder/mystamps/src/test/java/ru/mystamps/web/util/extractor/SiteParserTest.java; puzzle at line #112; Space expected at 113:5; make sure all lines in the puzzle body have a single leading space.
```

Instead o

 > ERROR: /tmp/0pdd20171208-4-je7stx/php-coder/mystamps/src/test/java/ru/mystamps/web/util/extractor/SiteParserTest.java ...

I'd like to see

> ERROR: src/test/java/ru/mystamps/web/util/extractor/SiteParserTest.java ...

Note that in my example, I also removed `php-coder/mystamps` part.

**Comment by php-coder** [comment]
P.S. See there: https://github.com/php-coder/mystamps/commit/bb4f863ada5ae98a9656664e9c1c3453e09b0192#commitcomment-26140735

**Comment by yegor256** [comment]
@php-coder it's fixed, please check

**Comment by php-coder** [comment]
Ok, I check it when I'll see it next time.
