### ISSUE TITLE
0pdd.rb:32-34: We don't have an SVG badge for GitHub, w...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/0pdd#17]
The puzzle `15-a1d6817e` in `0pdd.rb` (lines 32-34) has to be resolved: We don't have an SVG badge for GitHub, which will show how many puzzles we have at the moment in the repo. Let's create it, in SVG format (and maybe in PNG too).

The puzzle was created by Yegor Bugayenko on 13-Dec-16. 

Estimate: 30 minutes, Role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by 0pdd** [comment]
The puzzle `15-a1d6817e` has disappeared from the source code, that's why I closed this issue.

**Comment by yegor256** [comment]
@rultor release, tag is `0.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.3`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
