### ISSUE TITLE
Assign milestone for task

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/0pdd#173]
Could be great to assign GitHub milestone for job. What do you think? For now it is manual step afaik.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar not a bad idea, but how will we know which milestone to assign?

**Comment by yegor256** [comment]
@t-izbassar well, that will mean that programmers will make management decisions, which is not exactly how this should work. Programmers must only care about scope, while priorities of tasks must be set by managers. The only thing we can do, I believe, is to configure milestone assignment rules somehow in `.0pdd.yml`... WDYT?

**Comment by t-izbassar** [comment]
@yegor256 yes, valid points. It made much more sense in my personal project where I'm the dev and the manager)

Regarding yml - the only thing is that pdd can create milestones for projects but not assign it. That seems impossible. And there are no so much sense in creating milestones in `.0pdd.yml` when they can be created manually. I will try to think about it. Maybe the `0crat` should do it automatically somehow.

**Comment by t-izbassar** [comment]
Will come up with issue in `0crat` repo as he is the man making management decision)

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#173` is not assigned, can't get start time

**Comment by yegor256** [comment]
@t-izbassar right, thanks!

**Comment by 0crat** [comment]
Job [#173](https://github.com/yegor256/0pdd/issues/173) was not in scope
