### ISSUE TITLE
0pdd user listed as being banned from assigning to a job

### ISSUE THREAD

**Issue by rok-povsic** [yegor256/0pdd#176]
Action:
Messaging `0crat status` in an issue that bot *0pdd* opened (is an author of).

Result:
In the reply, `0pdd` lists itself as the user being banned from assigning to the job because it is the author of the issue.

Expected result:
`0pdd` should not be listed as it's not a real user/DEV and cannot be assigned to a job in any case.

See [here](https://github.com/yegor256/jpeek/issues/112#issuecomment-363709561) for an example.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rok-povsic this "bug" is not relevant to 0pdd. Please, report it to Zerocrat repository. Also, I would not recommend to report it there, since Zerocrat has no idea who is a bot and who is not. All users are equal to it.

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#176` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#176](https://github.com/yegor256/0pdd/issues/176) was not in scope
