### ISSUE TITLE
0pdd comments "All puzzles are solved" in all repo's opened and closed tickets

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/0pdd#178]
1) git push with new puzzle (and also one puzzle removed)
2) 0pdd closes the removed puzzle's Issue and opens a new one for the new puzzle - OK
3) 0pdd comments on all the Issues (both opened and closed): "``@0pdd All puzzles are solved"

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil can you give an example? Where did it happen?

**Comment by yegor256** [comment]
@amihaiemil I see it myself, here for example: https://github.com/zerocracy/farm/issues/89#issuecomment-368227489

**Comment by 0crat** [comment]
Thanks for your contribution, @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)! If you would be a member of [the project](https://www.0crat.com/p/C3T46CUJJ), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.2`

**Comment by yegor256** [comment]
@amihaiemil I believe it's fixed

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#178](https://github.com/yegor256/0pdd/issues/178) is now out of scope
