### ISSUE TITLE
Improve puzzle format description

### ISSUE THREAD

**Issue by ralfw** [yegor256/0pdd#181]
Add syntax for puzzles to https://github.com/yegor256/pdd#how-to-format (or wherever it's relevant). This way it would be unambiguous how to format a puzzle. Examples always leave room for misunderstanding and require abstraction by every reader.

Of course, examples are easier to read than a syntax spec. So the spec is there only in case of doubt or error.

Example

```
PUZZLE ::= "@todo" TICKET [ PARAMS ] [ description ].
TICKET ::= "#" ticketId.
PARAMS ::= [ ":" ] [ TIMEBOX ] [ ROLE ].
TIMEBOX ::= durationInMinutes "min".
ROLE ::= "/" [ "REV" | ... ]. // add further roles as needed

ticketId ::= The numer of a GitHub ticket, e.g. 23.
durationInMinutes ::= e.g. 30
description ::= a short one line text to describe the puzzle
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ralfw that's a good idea indeed, but it belong to this repository:  https://github.com/yegor256/pdd Can you please submit it there?

**Comment by ralfw** [comment]
done
