### ISSUE TITLE
CodeCov DiffCheck check is configured wrong

### ISSUE THREAD

**Issue by SilasReinagel** [yegor256/0pdd#187]
One of the CI checks is a code coverage diff check. This may cause the PR to fail even if DEV is fixing existing Rubocop violation. 

Diff check should be allowed to be 0% when code change is cosmetic only. 

https://github.com/yegor256/0pdd/pull/186

https://codecov.io/gh/yegor256/0pdd/compare/4e5181939d6e7cca184c2f5024d1b42ecf63bfb0...e8c58d0e0b371c608e7e3fca2ddb8efb06747bbf

http://www.rubydoc.info/gems/rubocop/0.43.0/RuboCop/Cop/Style/SafeNavigation

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@SilasReinagel I don't think it's technically possible. And I don't really understand what it's for. A check is a check.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by SilasReinagel** [comment]
@yegor256 More importantly, if the checks are configured wrong and the ARC won't fix them or approve tickets to fix them, then this project is not worth contributing to. 

DEVs only want to work on project with correctly configured and enforced policies.

**Comment by yegor256** [comment]
@SilasReinagel we don't "fail PRs" but anything except Rultor. Everything else is just for information. If you know how to fix something, please suggest. I didn't get the problem with this ticket. Codecov reports when coverage drops. Don't drop the coverage and it won't complain. It's simple.

**Comment by SilasReinagel** [comment]
@yegor256 Okay. If checks are just for information, then this check is fine.
