### ISSUE TITLE
0pdd didn't recognize puzzle removal

### ISSUE THREAD

**Issue by g4s8** [yegor256/0pdd#189]
I deleted puzzle comment in https://github.com/zerocracy/farm/pull/851 PR and it was merged, but ticket with this puzzle is still open: https://github.com/zerocracy/farm/issues/835

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@yegor256 same here: https://github.com/zerocracy/farm/issues/833 PR was merged (https://github.com/zerocracy/farm/pull/839) but ticket is open

**Comment by yegor256** [comment]
@g4s8 it was a temporary issue with HTTPS certificates. On the next push to the repo the puzzle will be closed.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
