### ISSUE TITLE
Too many notifications!

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/0pdd#197]
Can we make 0pdd more silent? It leaves way too many comments. It comments on Issue and also on commits + also leaves comments informing on what is still open or closed.

With each merged PR, I am flooded with notifications/emails (minimum 10 mails/merged PR). This becomes impractical, since I simply delete them, (I don't have time anyway to go through everything) and may even lose some important notification which happens to come in the same batch.

I think we could make this configurable from ``.0pdd.yml`` or even remove commenting on commits entirely -- those are really useless IMO.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by artem-p** [comment]
Totally agree. I have to create gmail filter to automatically archive these notifications. And I only have a few puzzles.

**Comment by 0crat** [comment]
The job [#197](https://github.com/yegor256/0pdd/issues/197) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1100857355); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#197` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.30`

**Comment by yegor256** [comment]
@rultor release, tag is `0.30`

**Comment by yegor256** [comment]
@rultor release, tag is `0.30`

**Comment by yegor256** [comment]
@amihaiemil try its new version, see README

**Comment by amihaiemil** [comment]
@yegor256 looks nice, thanks. I'll open more bugs if I find any problems with it. :)
