### ISSUE TITLE
0pdd.rb:248-250: Need to figure out the correct way to...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/0pdd#198]
The puzzle `194-4ac81527` from #194 has to be resolved:

https://github.com/yegor256/0pdd/blob/6fc444d0a7b0d333a0ea3f780a7c3dce583f69c3/0pdd.rb#L248-L250

The puzzle was created by yegor256 on 20-Apr-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#198](https://github.com/yegor256/0pdd/issues/198) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#198](https://github.com/yegor256/0pdd/issues/198) assigned to @vl3[/z](https://www.0crat.com/u/vl3), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1551534210); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@vl3[/z](https://www.0crat.com/u/vl3) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @vl3[/z](https://www.0crat.com/u/vl3) resigned from [#198](https://github.com/yegor256/0pdd/issues/198), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @vl3[/z](https://www.0crat.com/u/vl3)

**Comment by 0crat** [comment]
The job [#198](https://github.com/yegor256/0pdd/issues/198) assigned to @liligga[/z](https://www.0crat.com/u/liligga), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1750811497); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#198](https://github.com/yegor256/0pdd/issues/198) assigned to @golyalpha[/z](https://www.0crat.com/u/golyalpha), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1760632942); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/0pdd/issues/198#issuecomment-399903652))

@krzyk This is what I know about this job in [C3T46CUJJ](https://www.0crat.com/p/C3T46CUJJ), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#198](https://github.com/yegor256/0pdd/issues/198) is [in scope](http://www.zerocracy.com/policy.html#14) for 2mon
  * The role is `DEV`
  * The job is assigned to @golyalpha[/z](https://www.0crat.com/u/golyalpha) for [4hr](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @golyalpha[/z](https://www.0crat.com/u/golyalpha) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @vl3[/z](https://www.0crat.com/u/vl3): User was resigned from the ticket
    * @liligga[/z](https://www.0crat.com/u/liligga): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3T46CUJJ?q=%7Bjob%3A%27gh%3Ayegor256%2F0pdd%23198%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@golyalpha[/z](https://www.0crat.com/u/golyalpha) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by golyalpha** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/yegor256/0pdd/issues/198#issuecomment-402036889))

@golyalpha The user @golyalpha[/z](https://www.0crat.com/u/golyalpha) resigned from [#198](https://github.com/yegor256/0pdd/issues/198), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @golyalpha[/z](https://www.0crat.com/u/golyalpha)

**Comment by 0crat** [comment]
@pdacostaporto[/z](https://www.0crat.com/u/pdacostaporto) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by pdacostaporto** [comment]
@0crat wait for review #232

**Comment by 0crat** [comment]
> @0crat wait for review #232  ([here](https://github.com/yegor256/0pdd/issues/198#issuecomment-405147648))

@pdacostaporto The impediment for [#198](https://github.com/yegor256/0pdd/issues/198) was registered successfully by @pdacostaporto[/z](https://www.0crat.com/u/pdacostaporto)

**Comment by 0pdd** [comment]
The puzzle `194-4ac81527` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @pdacostaporto[/z](https://www.0crat.com/u/pdacostaporto)

**Comment by 0crat** [comment]
The job [#198](https://github.com/yegor256/0pdd/issues/198) is now out of scope
