### ISSUE TITLE
github_tickets.rb:116-117: Replace body with Template...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/0pdd#199]
The puzzle `195-ac2e468f` from #195 has to be resolved:

https://github.com/yegor256/0pdd/blob/80b4d00ee8d31a99be4bc021fefaf5a4700ef3ce/objects/github_tickets.rb#L116-L117

The puzzle was created by rultor on 23-Apr-18. 

Estimate: 60 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@pbenety[/z](https://www.0crat.com/u/pbenety) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by pbenety** [comment]
@0crat waiting for review #218

**Comment by 0crat** [comment]
> @0crat waiting for review #218  ([here](https://github.com/yegor256/0pdd/issues/199#issuecomment-397334966))

@pbenety The impediment for [#199](https://github.com/yegor256/0pdd/issues/199) was registered successfully by @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by 0pdd** [comment]
The puzzle `195-ac2e468f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by 0crat** [comment]
The job [#199](https://github.com/yegor256/0pdd/issues/199) is now out of scope
