### ISSUE TITLE
A couple of ideas

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/0pdd#2]
Since this is at the beginning of its life, I assume this is the right moment to suggest some ideas.

1) Instead of webhooks, you could spin a checker somewhere, that would read notifications and post them to the /hook endpoint? I wrote such an EJB for a project of mine and decided to pull it out and make it reusable. [Here](https://github.com/opencharles/mention-notifications-ejb) it is. 
The user doesn't have to do any settings to the repo and the load is small, only containing the repo's fullname and issue number where the bot was mentioned. The lookup logic, avoiding spam and whatnot is up to the receiver to implement, 

I think, instead of having it check my whole repo at every ``push``, it would be more efficient to have it check when I tell it to: "@ 0pdd check please" - you could have a script for rultor at merge time: check for todo's in the changed files and comment if there are any.

2) Why the write access needs? You already have rultor for automatic merging, so you might as well have it make pull requests and ask rultor to merge. I would add ``0pdd`` as a commander in ``.rultor.yml``. This way I could also check that the puzzles were correctly removed and see what other changes the bot did to my repo. Of course, if I choose to trust it completely, I add it as an architect and rultor won't ask for review.

I mean, if I like your work enough to use 0pdd, chances are very high that I already use rultor, so I have 2 of your bots, both needing write access. Besides, for write access, someone has to log into the bots account and accept the invitation and that takes time :)

**Comment by yegor256** [comment]
@amihaiemil good questions, but too many for one ticket. Can you please submit separate tickets for each questions? Thanks!

**Comment by amihaiemil** [comment]
@yegor256 I opened #4 and #5 :)
