### ISSUE TITLE
chat bot

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#20]
Let's create a chat bot, which will respond to GitHub messages, with some status information about puzzles.

**Comment by yegor256** [comment]
Won't do it. Maybe later...

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#20` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#20](https://github.com/yegor256/0pdd/issues/20) was not in scope
