### ISSUE TITLE
 warning: setlocale: LC_ALL: cannot change locale (UTF-8)

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/0pdd#210]
On 0pdd.com, we see some strange error messages both in the latest comits list and on the footer which is supposed to contain the build number, ruby eversion etc:

![image](https://user-images.githubusercontent.com/6305156/40411797-1a2b6010-5e7a-11e8-8cff-1cce7c714816.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.3`

**Comment by yegor256** [comment]
@amihaiemil fixed, thanks!

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#210](https://github.com/yegor256/0pdd/issues/210) is now out of scope
