### ISSUE TITLE
How to disable status comments from the bot in the parent issue?

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#219]
I see that the bot now posts comments to the parent issue about the current status, like this:

> the puzzle #882 is still not solved.

How I can disable such behavior? For me these new comments look like spam messages.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@php-coder[/z](https://www.0crat.com/u/php-coder) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@php-coder check the "suppress" section: https://github.com/yegor256/0pdd#how-to-configure

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#219` is not assigned, can't get performer

**Comment by php-coder** [comment]
@yegor256 Thanks!

That's sad that you don't support backward compatible behavior :(

**Comment by php-coder** [comment]
Suppression don't work:
```
no implicit conversion of String into Integer

/app/objects/job.rb:39:in `dig'
/app/objects/job.rb:39:in `proceed'
/app/objects/job_starred.rb:33:in `proceed'
/app/objects/job_recorded.rb:32:in `proceed'
/app/objects/job_emailed.rb:35:in `proceed'
/app/objects/job_commiterrors.rb:36:in `proceed'
/app/objects/job_detached.rb:48:in `exclusive'
/app/objects/job_detached.rb:36:in `block in proceed'
/app/objects/job_detached.rb:36:in `fork'
/app/objects/job_detached.rb:36:in `proceed'
/app/0pdd.rb:342:in `block in '
```
See here for more info: https://github.com/php-coder/mystamps/commit/66aca64ea892bf7c3360a656b855cbd842288f7e#commitcomment-29369514

Looks like https://github.com/yegor256/0pdd/issues/206
