### ISSUE TITLE
0pdd.rb:33-35: Page not found is not implemented. When ...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/0pdd#22]
The puzzle `3-41f7e700` in `0pdd.rb` (lines 33-35) has to be resolved: Page not found is not implemented. When I open a URL that doesn't exist I see a default sinatra "not found" page, which is annoying.

The puzzle was created by Yegor Bugayenko on 13-Dec-16. 

Estimate: 15 minutes, Role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by 0pdd** [comment]
The puzzle `3-41f7e700` has disappeared from the source code, that's why I closed this issue.

**Comment by yegor256** [comment]
@rultor release, tag is `0.4`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
