### ISSUE TITLE
Update/remove gemnasium badge

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#220]
`README.md` file has gemnasium badge that at this moment shows the message "FIXME Migrate to GitLab". Consider updating/removing this badge.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@php-coder[/z](https://www.0crat.com/u/php-coder) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#220` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
