### ISSUE TITLE
0pdd should mention github user name not real name

### ISSUE THREAD

**Issue by krzyk** [yegor256/0pdd#223]
When 0pdd creates issues from puzzles it also mentions the puzzle created, e.g.: `The puzzle was created by Tolegen Izbassar on 22-May-18.`

I think it would be better if instead of the real name of the author it would mention the github nick + make it a link to the user profile (not a mention).

It would make it more consistent with the rest of the repo comments.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@krzyk we take this information from the XML file produced by `pdd` Rugy gem. Thus, please report this to the `pdd` repository: https://github.com/yegor256/pdd

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#223` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
