### ISSUE TITLE
Development setup needed

### ISSUE THREAD

**Issue by fybwid** [yegor256/0pdd#224]
It would be helpful if the project has a development preparation guide, especially for people who want to contribute, so the process works.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by fybwid** [comment]
@yegor256
Something like this:
1. Clone this repository:
`git clone git@github.com:yegor256/0pdd.git`
2. Install project requirement:
`bundle install`
3. Create `config.yml`
4. Run the project
`ruby 0pdd.rb`
For C9 user: `ruby 0pdd.rb -p $PORT -o $IP
5. Testing
`rake`
PS.
Ruby version: 2.3.3

**Comment by yegor256** [comment]
@fybwid well, this would be something very primitive :) We just assume that our developers know that to start working with a Git Ruby project they have to clone first and then `bundle install`. I added a bit in 745073b If you need something more specific, please open a new ticket.

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#224` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
