### ISSUE TITLE
repository renaming

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#23]
What will happen if repository is renamed? We will re-submit all tickets to a new one -- that would be a big disaster. Let's find a way to prevent that.

**Comment by yegor256** [comment]
I guess I was wrong, we won't resubmit them, everything will work fine.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/0pdd#23`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#23` is not in scope.
