### ISSUE TITLE
Search functionality for get '/p'  page

### ISSUE THREAD

**Issue by liligga** [yegor256/0pdd#236]
I think it would be easier and more userfriendly to have a search bar to look for task in a specific repo than having to change url(as it is now) to match `user/repo` pattern. This includes backend task to create a search incorporated into that request(`get '/p' `) as well as frontend search field with submit button. 

- [ ] Backend: look for repo depending on form submitted and url params(get request both) 
- [ ] Frontend: form with a search field

**Comment by yegor256** [comment]
@liligga I'm not sure I get it. You want to find a task in which page? Can you give the exact URL?

**Comment by liligga** [comment]
@yegor256 So basically to get list of puzzles from this very repo is to type `http://www.0pdd.com/p?name=yegor256/0pdd` in address bar. What I am proposing here is to have one or two inputs to enter for instance `yegor256/0pdd` and press button to have that same list of puzzles.

**Comment by yegor256** [comment]
@liligga well, that may work but I don't see a real point in such a functionality. Each project has its own page, which it gives to its users. Who and why will go to our front page and search for projects? What for?

**Comment by liligga** [comment]
@yegor256 Ok I see. You can close the issue then.

**Comment by yegor256** [comment]
@liligga yes, please

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#236` is not assigned, can't get performer
