### ISSUE TITLE
Specify labels in puzzle text

### ISSUE THREAD

**Issue by g4s8** [yegor256/0pdd#239]
Feature request:
Allow to specify Github issue labels in puzzle body text, e.g.:
```
// @todo #1:30min [bug] This class is broken ...
```
so 0pdd will submit this puzzle as a ticket with `bug` label even if was not specified in `tags` section in `.0pdd.yml`.
It may help to prioritize tickets for 0crat on code-review stage: ARC or REV may ask to add/remove `bug` label to mark a ticket as important/not-important, so it will save ARC's time because there will be no need to do additional actions when 0pdd submits a ticket.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@g4s8 that will give too much power to programmers, I'm afraid. Now only the architect can configure 0pdd via `.0pdd.yml`, but with this feature anyone will be able to manage Zerocrat in some way. Don't you think it's dangerous?

**Comment by g4s8** [comment]
@yegor256 yes, architect will have to merge todos more carefully, but he still can control final issue labels by asking to change it in the PR or reject it. In case of mistake (if incorrect labels was added to puzzle), he always can remove this issue from scope. It will be a little more work in merge process, but less in new issue analyzing.

**Comment by yegor256** [comment]
@g4s8 but why can't the architect just configure it in the `.0pdd.yml`?

**Comment by g4s8** [comment]
@yegor256 because `.0pdd.yml` is a global config, where each issue may have different priority/label. E.g. not every pdd puzzle is so important to add `bug` label.

**Comment by yegor256** [comment]
@g4s8 and you want the decision about importance/priority to be made by programmers, instead of the architect??

**Comment by g4s8** [comment]
@yegor256 no, you didn't get it. I think architect should be able to specify the priority of new puzzle right in the pull request by asking performer to add or remove some labels.

**Comment by yegor256** [comment]
@g4s8 sounds like an overkill for me... Moreover, 0pdd doesn't parse the source code, it's done by this Gem: https://github.com/yegor256/pdd We can teach that gem to understand some "label" or "markers" in the text, yes. What to do with them later, is what 0pdd has to decide. So, it's a two-steps task...

**Comment by g4s8** [comment]
@yegor256 ok, so closing it

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#239` is not assigned, can't get performer
