### ISSUE TITLE
0pdd failed with "554 Message rejected"

### ISSUE THREAD

**Issue by g4s8** [yegor256/0pdd#240]
0pdd failed to submit a puzzle with message:
```
554 Message rejected: Sending suspended for this account. For more information, please check the inbox of the email address associated with your AWS account.
```

see https://github.com/zerocracy/farm/commit/11a490b4be23bbda5933e7e3fc1f7417ff4cdecc#commitcomment-30568173

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@g4s8 this is solved already

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#240` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
