### ISSUE TITLE
Ruby version 2.5.1, clean install, `rake` errors out with missing `mvn`

### ISSUE THREAD

**Issue by snugghash** [yegor256/0pdd#242]
Ruby 2.3+ (2.5.1) from arch linux official repo, Rubygems installed.
```
gem install bundler
bundle update 
```

Successful update occurs.
```
rake
```
Finds many outdated gems, and errors out about missing mvn. This is an undocumented system dependency of Maven that is not mentioned in the `README.md`.

This didn't cost me any developer time, but this did make me procrastinate and not work on this first time I found it. This is a bug of incomplete documentation of the project.

I'd like for maven to be in the same line that says we need Ruby 2.3+.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@snugghash fixed in 7e18c3f thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#242` is not assigned, can't get performer
