### ISSUE TITLE
0pdd is broken

### ISSUE THREAD

**Issue by g4s8** [yegor256/0pdd#244]
0pdd is not submitting new issues in few projects and is not closing issues when puzzle delete (e.g. https://github.com/zerocracy/farm/issues/1705) . At the same time it's working fine in few another projects.
It's is not working in these projects: https://github.com/zerocracy/farm and https://github.com/sunsofterp/portal
I've checked that all puzzles have valid format with `pdd` tool:
```sh
pdd --source=$(pwd) --verbose --file=/dev/null
```

I'm not entirely sure that it is related, but bug https://github.com/yegor256/0pdd/issues/240 was happend before this bug. And now I'm not receiving any error from 0pdd by email.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.4`

**Comment by 0crat** [comment]
The job [#244](https://github.com/yegor256/0pdd/issues/244) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/2740560289); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#244` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.4`

**Comment by yegor256** [comment]
@g4s8 should be OK now

**Comment by 0crat** [comment]
Job was finished in 13 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#244](https://github.com/yegor256/0pdd/issues/244) is now out of scope

**Comment by g4s8** [comment]
@yegor256 it actually didn't help: 0pdd is still not working in these projects:  https://github.com/zerocracy/farm https://github.com/sunsofterp/portal

**Comment by g4s8** [comment]
@yegor256 it started to work after 21 Oct 2018 in all projects simultaneously: 0pdd submitted a lot of tickets for one commit/webhook, it looks like it's stable now, thanks.
