### ISSUE TITLE
0pdd Github webhook URL is responding with 404

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/0pdd#255]
Beginning 6 hours ago, the webhook `http://www.0pdd.com/hook/github` started responding with `404` error. This prevented any puzzles getting refreshed on our project.

We have not changed any webhook configs. Also, multiple unrelated repos appear to be receiving the 404 error, suggesting that this is a problem in `0pdd` side.

See https://www.rehttp.net/i?u=http%3A%2F%2Fwww.0pdd.com%2Fhook%2Fgithub

![image](https://user-images.githubusercontent.com/1917892/49122741-a6d74a00-f2f0-11e8-81c8-ea5bfd5e82e6.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@carlosmiranda @yegor256 same issue for me. It seems that affected only private repos.

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.13`

**Comment by yegor256** [comment]
@carlosmiranda fixed, thanks for reporting!

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#255` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
