### ISSUE TITLE
Update pdd to take into account the latest changes

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#257]
It seems like 0pdd uses the last released version of pdd that is 0.20.3:

https://github.com/yegor256/0pdd/blob/b917d5350744c0428da22454efa336f789f4759d/Gemfile.lock#L90

It was released on 5 Mar and doesn't include changes after that date.

For example, https://github.com/yegor256/pdd/issues/104 has been fixed in https://github.com/yegor256/pdd/commit/ac348eefbfebef685f180ee7c8f1031d64af242e on 11 Jul but because 0pdd uses the old version, the issues is still here (proof: https://github.com/php-coder/mystamps/issues/993).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@php-coder[/z](https://www.0crat.com/u/php-coder) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.14`

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.14`

**Comment by yegor256** [comment]
@php-coder done

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#257` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
