### ISSUE TITLE
It is not possible to specify a list of excluded files.

### ISSUE THREAD

**Issue by DronMDF** [yegor256/0pdd#259]
My project include cpplint.py, which contains many comments not compatible with pdd.
This was not a problem until the yegor256/pdd#106 was closed.

This led to the fact that 0pdd refuses to process my project.
Apparently I should be able to specify a list of files that should be excluded.
But I can not do this through the 0pdd.yml.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dronmdf[/z](https://www.0crat.com/u/dronmdf) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@DronMDF why can't you do this via `.pdd` file?

**Comment by DronMDF** [comment]
@yegor256 Yes, I can do it over --exclude...
In december i can't find this solution.
I close this bug.
This is solved.

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#259` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
