### ISSUE TITLE
emails on all submit/close operations

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#26]
Let's send emails when we submit new issues and close existing one, just for the sake of traceability.

**Comment by yegor256** [comment]
@Eugst can you try to fix this?

**Comment by Eugst** [comment]
@yegor256 Yes, I will.

**Comment by yegor256** [comment]
@Eugst I will fix it myself

**Comment by yegor256** [comment]
@rultor release, tag is `0.13`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#26` was not in scope
