### ISSUE TITLE
0pdd answers with 404

### ISSUE THREAD

**Issue by Serranya** [yegor256/0pdd#261]
I am trying to use 0pdd for my project at https://github.com/Serranya/de.serra.condorcat

For some reason 0pdd answers to my webhook only with 404: https://www.rehttp.net/d?u=http%3A%2F%2Fwww.0pdd.com%2Fhook%2Fgithub&t=1546940172950

Other requests directly before mine are getting a 200.

I also got no mail from 0pdd explaining me what is wrong.

What I did to set up 0pdd was:

Add a webhook:
![grafik](https://user-images.githubusercontent.com/1206309/50822380-ee121b00-1331-11e9-915c-976a95959281.png)
Push some puzzles: https://github.com/Serranya/de.serra.condorcat/commit/b950932feacdf5567b060dfdde5c3791921d2e95

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@serranya[/z](https://www.0crat.com/u/serranya) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by Serranya** [comment]
Seems like it is breaking here https://github.com/yegor256/0pdd/blob/master/0pdd.rb#L397

**Comment by yegor256** [comment]
@Serranya definitely a bug, thanks for the PR!

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.15`

**Comment by yegor256** [comment]
@Serranya should be fine now, thanks for your help!
