### ISSUE TITLE
mail format is not accepting my valid email

### ISSUE THREAD

**Issue by ammaratef45** [yegor256/0pdd#263]
I'm getting that error from 0pdd

> w13:0: ERROR: Element 'email': [facet 'pattern'] The value 'a_atef45@yahoo.com' is not accepted by the pattern '([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})'.
> 13:0: ERROR: Element 'email': 'a_atef45@yahoo.com' is not a valid value of the local atomic type.
> 25:0: ERROR: Element 'email': [facet 'pattern'] The value 'a_atef45@yahoo.com' is not accepted by the pattern '([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})'.
> 25:0: ERROR: Element 'email': 'a_atef45@yahoo.com' is not a valid value of the local atomic type.

Is my email not valid or what?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ammaratef45 I can't find where this error is coming from. We don't have that in our code. Can you please show the full log? Where I can find more info?

**Comment by ammaratef45** [comment]
> I wasn't able to retrieve PDD puzzles from the code base and submit them to GitHub. If you think that it's a bug on our side, please submit it to [yegor256/0pdd](https://github.com/yegor256/0pdd/issues):
> 
> > XML has 4 errors w13:0: ERROR: Element 'email': [facet 'pattern'] The value '[a_atef45@yahoo.com](mailto:a_atef45@yahoo.com)' is not accepted by the pattern '([0-9a-zA-Z](%5B-.%5Cw%5D*%5B0-9a-zA-Z%5D)_@([0-9a-zA-Z][-\w]_[0-9a-zA-Z].)+[a-zA-Z]{2,9})'. 13:0: ERROR: Element 'email': '[a_atef45@yahoo.com](mailto:a_atef45@yahoo.com)' is not a valid value of the local...
> 
> Please, copy and paste this stack trace to GitHub:
> 
> ```
> RuntimeError
> XML has 4 errors
> w13:0: ERROR: Element 'email': [facet 'pattern'] The value 'a_atef45@yahoo.com' is not accepted by the pattern '([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})'.
> 13:0: ERROR: Element 'email': 'a_atef45@yahoo.com' is not a valid value of the local atomic type.
> 25:0: ERROR: Element 'email': [facet 'pattern'] The value 'a_atef45@yahoo.com' is not accepted by the pattern '([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})'.
> 25:0: ERROR: Element 'email': 'a_atef45@yahoo.com' is not a valid value of the local atomic type.
> <?xml version="1.0"?>
> <puzzles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.0pdd.com/puzzles.xsd" date="2016-12-08T12:00:49Z" version="0.0.0">
>   <puzzle alive="true">
>     <issue>unknown</issue>
>     <ticket>1</ticket>
>     <estimate>10</estimate>
>     <role>DEV</role>
>     <id>1-5e0e29d8</id>
>     <lines>7-7</lines>
>     <body>create mvvm model (see main page) for this page</body>
>     <file>attendance/lib/login_page.dart</file>
>     <author>@ammaratef45</author>
>     <email>a_atef45@yahoo.com</email>
>     <time>2019-01-16T17:08:45Z</time>
>     <children/>
>   </puzzle>
>   <puzzle alive="true">
>     <issue>unknown</issue>
>     <ticket>1</ticket>
>     <estimate>60</estimate>
>     <role>DEV</role>
>     <id>1-32499cde</id>
>     <lines>13-13</lines>
>     <body>learn how to use test and write unit tests</body>
>     <file>attendance/test/widget_test.dart</file>
>     <author>@ammaratef45</author>
>     <email>a_atef45@yahoo.com</email>
>     <time>2019-01-16T17:10:23Z</time>
>     <children/>
>   </puzzle>
> </puzzles>
> 
> /app/objects/safe_storage.rb:44:in `valid'
> /app/objects/safe_storage.rb:37:in `save'
> /app/objects/upgraded_storage.rb:47:in `save'
> /app/objects/sync_storage.rb:35:in `block in save'
> /app/objects/sync_storage.rb:35:in `synchronize'
> /app/objects/sync_storage.rb:35:in `save'
> /app/objects/puzzles.rb:46:in `save'
> /app/objects/puzzles.rb:34:in `deploy'
> /app/objects/job.rb:38:in `proceed'
> /app/objects/job_starred.rb:33:in `proceed'
> /app/objects/job_recorded.rb:32:in `proceed'
> /app/objects/job_emailed.rb:35:in `proceed'
> /app/objects/job_commiterrors.rb:36:in `proceed'
> /app/objects/job_detached.rb:48:in `exclusive'
> /app/objects/job_detached.rb:36:in `block in proceed'
> /app/objects/job_detached.rb:36:in `fork'
> /app/objects/job_detached.rb:36:in `proceed'
> /app/0pdd.rb:354:in `block in <top (required)>'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/logger.rb:15:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:231:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:224:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
> /app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
> /app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/handler/webrick.rb:86:in `service'
> /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/webrick/httpserver.rb:140:in `service'
> /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/webrick/httpserver.rb:96:in `run'
> /app/vendor/ruby-2.6.0/lib/ruby/2.6.0/webrick/server.rb:307:in `block in start_thread'
> ```

**Comment by ammaratef45** [comment]
@yegor256 
I changed the mail of my GitHub user to my Gmail `ammar.atef45@gmail.com` and it's working.

Maybe you have a problem with the `_` letter.

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.16`

**Comment by yegor256** [comment]
@ammaratef45 you are right, it was a bug in the code, fixed and tested in af79f5b. Should work fine now (after release).

**Comment by ammaratef45** [comment]
@yegor256 Nice :+1:

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#263` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
