### ISSUE TITLE
Unexistent file in issue description

### ISSUE THREAD

**Issue by emilianodellacasa** [yegor256/0pdd#264]
In a private repository pdd is creating correctly the issue, however the file is not correct.

Attaching the image to show the problem:

![pdd](https://user-images.githubusercontent.com/304924/51825375-ef0ceb80-22e4-11e9-832a-9e3072b45f7c.PNG)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by emilianodellacasa** [comment]
It was an error in the configuration file

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#264` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
