### ISSUE TITLE
0pdd failed to pull

### ISSUE THREAD

**Issue by g4s8** [yegor256/0pdd#274]
0pdd is raising same error for each commit in one [repo](https://github.com/g4s8/matchers-json):
> Your branch and 'origin/master' have diverged,
and have 1 and 25 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
First, rewinding head to replay your work on top of it...

E.g. here:
https://github.com/g4s8/matchers-json/commit/b16a7328c58b568e04666af91392fe2b1c046914#commitcomment-34150898

I'm not sure why this happens, but most probably because I fixed one commit message with force push, not sure.

It would be good to have reset option or automatically reset git on similar error

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@lastk can you check?

**Comment by g4s8** [comment]
@yegor256 thanks, fixed

**Comment by 0crat** [comment]
Job [#274](https://github.com/yegor256/0pdd/issues/274) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#274` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#274](https://github.com/yegor256/0pdd/issues/274) is now out of scope

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
