### ISSUE TITLE
0pdd is not closing or opening tickets

### ISSUE THREAD

**Issue by g4s8** [yegor256/0pdd#276]
I've removed a puzzle and submitted few new puzzles in these commits:
https://github.com/January-ai/restaurant_crawling/commit/8fc3bbe075914ee998ca4df79cea2016bb04e222
https://github.com/January-ai/restaurant_crawling/commit/9a22023eff97a19cac8f62e759f4ef78aae6d8d6
but 0pdd ignored these commits, where it was supposed to close the ticket and open few new tickets.
I checked https://www.githubstatus.com/ and it's all fine with webhooks status.
Also, I tried to push empty commit to re-trigger webhooks, but it didn't help.
I checked puzzles with:
```bash
~/.gem/ruby/2.4.0/bin/pdd --source=$(pwd) --verbose --file=/dev/null && echo OK
```
and it returned OK - all puzzles are valid

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@yegor256 fixed

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#276` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
