### ISSUE TITLE
PDD failed to create a label

### ISSUE THREAD

**Issue by aivinog1** [yegor256/0pdd#281]
See this: https://github.com/aivinog1/omdb-api/issues/5#issuecomment-549050947

A @0pdd is already in the collaborator's list, but Github waiting for a response: 
![image](https://user-images.githubusercontent.com/25925932/68072906-70863280-fdbd-11e9-82ce-e18013b4bb49.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@aivinog1 this was a temporary issue, solved already

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#281` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by rocket-3** [comment]
@yegor256 The same error occurs now.
