### ISSUE TITLE
pdd doesn't recognize and document task when in test file

### ISSUE THREAD

**Issue by ChameleonTartu** [yegor256/0pdd#283]
When I leave puzzle in test file. `MyControllerTest.java` under `src/test/java` folder it looks as on picture below:

![image](https://user-images.githubusercontent.com/13621271/67152015-37cf5f00-f2cf-11e9-9448-4f75f97f26ef.png)

I expected it to write name of the test file and line as well as beginning of description.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@chameleontartu[/z](https://www.0crat.com/u/chameleontartu) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.21`

**Comment by yegor256** [comment]
@ChameleonTartu should be OK now, thanks for reporting this

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#283` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by ChameleonTartu** [comment]
@yegor256 Thx!
