### ISSUE TITLE
0crat/0pdd is not closing issue for merged PR

### ISSUE THREAD

**Issue by fanifieiev** [yegor256/0pdd#285]
The issue: [998](https://github.com/yegor256/takes/issues/998) is not being closed, even though its PR: [1001](https://github.com/yegor256/takes/pull/1001) has been merged and finished.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@fanifieiev[/z](https://www.0crat.com/u/fanifieiev) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#285` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
