### ISSUE TITLE
Allow 0pdd to create puzzles based on main branch

### ISSUE THREAD

**Issue by raboley** [yegor256/0pdd#293]
now that GitHub is moving from doing master branch to main branch as default, it would be nice if 0pdd worked on main branch and not only master.

thank you!

  - You have all pre-requisites listed in README.md installed
  - You are sure that you are not reporting a duplicate (search all issues)
  - You say "is broken" or "doesn't work" in the title
  - You tell us what you are trying to do
  - You explain the results you are getting
  - You suggest an alternative result you would like to see

This article will help you understand what we are looking for: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

Thank you for your contribution!

**Comment by mbao01** [comment]
@raboley Hi 👋🏾 this issue (also reported here - #313) has been fixed and deployed. Please can you close this issue if all looks good? Thanks.
