### ISSUE TITLE
https://www.0pdd.com certificate has expired

### ISSUE THREAD

**Issue by andreoss** [yegor256/0pdd#296]
<pre>
* $JAVA_HOME/bin/keytool -printcert -sslserver www.0pdd.com:443
Certificate #0
====================================
Owner: CN=0pdd.com, OU=PositiveSSL, OU=Domain Control Validated
Issuer: CN=Sectigo RSA Domain Validation Secure Server CA, O=Sectigo Limited, L=Salford, ST=Greater Manchester, C=GB
Serial number: 6b346e868a52a3b530573b6d4407573c
Valid from: Wed Oct 23 03:00:00 MSK 2019 until: <b>Fri Oct 23 02:59:59 MSK 2020</b>
Certificate fingerprints:
         SHA1: 82:D7:47:88:DC:DD:9D:FC:9E:3C:8D:67:5D:21:38:82:DC:39:A4:C2
         SHA256: 74:31:80:60:43:83:89:D8:93:46:FD:3E:8E:1D:2C:F2:5C:F9:58:87:4C:3D:BF:73:1C:17:23:E8:28:D0:E9:B6
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

</pre>

**Comment by yegor256** [comment]
@andreoss fixed, thanks for reporting!

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#296` is not assigned, can't get performer
