### ISSUE TITLE
Issues not created from commit

### ISSUE THREAD

**Issue by olegmoz** [yegor256/0pdd#297]
PDD bot is expected to create new issue from `@todo` puzzles when PR is merged in master branch. However it stopped to produce such issues for Artipie repositories. Removed puzzles do not cause issues to be closed as well. Examples of PRs that were merged, but ignored by PDD bot:
- https://github.com/artipie/docker-adapter/pull/359
- https://github.com/artipie/artipie/pull/776

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.22`

**Comment by yegor256** [comment]
@rultor release, tag is `0.30.22`

**Comment by yegor256** [comment]
@olegmoz should be fine now, I believe
