### ISSUE TITLE
Enforce accept invitation doesn't work `https://0pdd.com/invitation?repo=`

### ISSUE THREAD

**Issue by notsu** [yegor256/0pdd#325]
After I invited the `0pdd` user to my private repo and expected to see the bot accept an invitation within 30 minutes but it didn't do that. 

So, I tried to enforce to accept the invitation by opening https://0pdd.com/invitation?repo={org}/{repo} but this URL returns `ERR_CONNECTION_TIMED_OUT`.

Would you please give me a suggestion on how to solve it or have any workaround to fix it?

<img width="718" alt="Screen Shot 2565-03-14 at 02 48 07" src="https://user-images.githubusercontent.com/356022/158076419-3bb41f32-71e5-4800-8954-7cac52db9951.png">

**Comment by mbao01** [comment]
@notsu Hi 👋🏾 As I have confirmed, the root domain (`0pdd.com`) is not redirected to `www.0pdd.com`. While I look into the issue, please use `https://www.0pdd.com/invitation?repo={org}/{repo}`. Thanks

**Comment by notsu** [comment]
It works! Thank you a lot. 🙇
