### ISSUE TITLE
[major] Badge with statistics is broken and shows 0 alive, 0 total

### ISSUE THREAD

**Issue by php-coder** [yegor256/0pdd#367]
The page with repo stats (https://www.0pdd.com/p?name=php-coder/mystamps) shows "0 alive, 0 total" and a badge also shows this data.

**Comment by yegor256** [comment]
@mbao01 can you please help? It's urgent, it seems

**Comment by php-coder** [comment]
It's working now: `207 alive, 317 total.` and badge shows `99+/99+`

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#367` is not assigned, can't get performer
