### ISSUE TITLE
0pdd doesn't give any reaction on pings

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#373]
Check this out: https://github.com/yegor256/cactoos/issues/1566 The puzzle is gone from the code, but 0pdd doesn't react on webhooks. It responses with "Thanks yegor256/cactoos" but doesn't update the XML inside and doesn't close the ticket.

**Comment by yegor256** [comment]
@mbao01 please, help

**Comment by yegor256** [comment]
@mbao01 I reverted back the logic inside `puzzles.rb`. It seems that there was some code duplication, which was hard to understand. Let's reimplement it and submit a pull request again.

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#373` is not assigned, can't get performer
