### ISSUE TITLE
0pdd does not accept the inventation

### ISSUE THREAD

**Issue by kerelape** [yegor256/0pdd#380]
this is the repository: https://github.com/intechconst/intechconst.ru

The inventetion has been pending for 3 hours by now and the link in README doesn't open at all (I did replace the placeholder with `intechconst/intechconst.ru`).

**Comment by php-coder** [comment]
Any updates on this? I have the same issue with `php-coder/query2app` repository.

CC @yegor256

**Comment by yegor256** [comment]
@kerelape did you invite 0pdd user to the repository or to the organization? If the latter, it won't work, since GitHub API doesn't allow us to accept such invitations automatically :(

**Comment by kerelape** [comment]
@yegor256 repository

**Comment by php-coder** [comment]
The same here. Invitation is still in pending state.

**Comment by php-coder** [comment]
@yegor256 ping

As an invitation is still pending, it seems like 0pdd is unusable for new projects/users :-(

**Comment by yegor256** [comment]
@php-coder I'm on it

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#380` is not assigned, can't get performer

**Comment by php-coder** [comment]
@yegor256 Thank you!
