### ISSUE TITLE
0pdd.rb:23-25: We lose errors when they happen with the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/0pdd#39]
The puzzle `1-1c2ee73f` in `0pdd.rb` (lines 23-25) has to be resolved: We lose errors when they happen with the source code. They just drop into the log and that's it. Instead, we must email them to the repository owner or a predefined email from .0pdd.yml

The [puzzle](http://www.yegor256.com/2009/03/04/pdd.html) was created by Yegor Bugayenko on 22-Dec-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by 0pdd** [comment]
@yegor256 please pay attention to this new issue.

**Comment by 0pdd** [comment]
The puzzle `1-1c2ee73f` has disappeared from the source code, that's why I closed this issue. //cc @yegor256

**Comment by yegor256** [comment]
@rultor release, tag is `0.7`

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
