### ISSUE TITLE
Alternative to webhooks

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/0pdd#4]
Instead of having the users configure webhooks on their repos, you could have a running checker, that would check for notifications like comment mentions and ping the bot at /hook endpoint.

I wrote such a checker so [it](https://www.github.com/opencharles/mention-notifications-ejb), or something similar, could be used.

Instead of checking the whole repo at each push event, the bot would check it only when commanded. It could also be commanded by rultor after a merge.

**Comment by yegor256** [comment]
@amihaiemil but we don't need issues or mentions. We have to check the source code when a new Git `push` arrives. When it happens, we check the source code and create new GitHub issues, if new puzzles are found. Try it out in your project, you will see how it works.

**Comment by amihaiemil** [comment]
@yegor256 I understood the principle. This came as an alternative :)
