### ISSUE TITLE
0pdd is creating duplicate tickets

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/0pdd#40]
@0pdd is creating a lot of duplicate tickets in Xockets Layer project:

https://github.com/teamed/xockets-layer/issues

See screenshot here, where three puzzles were opened three times in the past 24 hours:

![image](https://cloud.githubusercontent.com/assets/1917892/21444567/c5e57a9e-c8e9-11e6-9372-97a13e1cc930.png)

**Comment by yegor256** [comment]
@carlosmiranda this is definitely a bug, thanks for reporting. It happens when 0pdd bot is creating an issue and then crashes for some reason and doesn't store the issue number in the XML. Then, later, when a new push happens to the master branch, a new issue is created again. This won't happen for a while, since the cause of that crash is gone, but may happen in the future. We have to find a solution.

**Comment by amihaiemil** [comment]
@yegor256 Wouldn't it be safer to just check the opened issues via Github API? I mean, find a puzzle in the code, calculate its id, and then check if there are any issues opened by 0pdd which have that id.

**Comment by yegor256** [comment]
@amihaiemil this "check if there are any issues..." operation will take a lot of time and API calls if GitHub repository is rather big (thousands of issues)

**Comment by carlosmiranda** [comment]
@yegor256 any updates on this one? We're seeing this behavior again in Xockets Layer, as well as old puzzles that are not being closed.

**Comment by 0pdd** [comment]
I see you're talking about me; I can't reply, I'm not a chat bot.

**Comment by yegor256** [comment]
@carlosmiranda I think I fixed it already. Let me monitor the situation for a few days.

**Comment by carlosmiranda** [comment]
@yegor256 thanks. However there are still a couple of tickets on XL that you were not able to close...

**Comment by yegor256** [comment]
@carlosmiranda is it still a problem or you can close the issue?

**Comment by carlosmiranda** [comment]
@yegor256 seems ok now. Thanks. :)

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#40` was not in scope
