### ISSUE TITLE
submit puzzles if they are alive and don't have issues

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#41]
Let's submit them, if they are alive, but without issues.

**Comment by yegor256** [comment]
@rultor release, tag is `0.10`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#41` was not in scope

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#349](https://github.com/yegor256/0pdd/issues/349), [#47](https://github.com/yegor256/0pdd/issues/47) are still not solved; solved: [#48](https://github.com/yegor256/0pdd/issues/48).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#47](https://github.com/yegor256/0pdd/issues/47) is still not solved; solved: [#349](https://github.com/yegor256/0pdd/issues/349), [#48](https://github.com/yegor256/0pdd/issues/48).

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#364](https://github.com/yegor256/0pdd/issues/364) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 all 3 puzzles are solved here: [#349](https://github.com/yegor256/0pdd/issues/349), [#47](https://github.com/yegor256/0pdd/issues/47), [#48](https://github.com/yegor256/0pdd/issues/48).
