### ISSUE TITLE
0pdd doesn't work?

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/0pdd#452]
1. I've added `0pdd` as a collaborator to my [repository](https://github.com/volodya-lombrozo/jtcop)
2. Added web hook to the `http://p.rehttp.net/http://www.0pdd.com/hook/github`
3. Created [PR](https://github.com/volodya-lombrozo/jtcop/pull/94) that have puzzles.

Expected behaviour: New puzzles (issues) are created.
Actual behaviour: Nothing happens.

Maybe I miss something?

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you help here, please?

**Comment by volodya-lombrozo** [comment]
@yegor256 Reminder

**Comment by yegor256** [comment]
@volodya-lombrozo use this URL: `https://p.rehttp.net/https://www.0pdd.com/hook/github`
