### ISSUE TITLE
puzzles.rb:87-89: Let's post notification messages to...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/0pdd#48]
The puzzle `41-15a94873` in [`objects/puzzles.rb`](https://github.com/yegor256/0pdd/blob/master/objects/puzzles.rb) (lines 87-89) has to be resolved: Let's post notification messages to tickets where other puzzles were waiting for the resolution of this one. Let's update them with a summary information of what is left.

The puzzle was created by Yegor Bugayenko on 15-Feb-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `41-15a94873` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#48` was not in scope

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
