### ISSUE TITLE
0pdd does not accepting the invite to the repository

### ISSUE THREAD

**Issue by h1alexbel** [yegor256/0pdd#483]
0pdd does not accepting the invite to the repository
It's critical for private repos

fix it, please

**Comment by lipetskplant** [comment]
The same problem persists

**Comment by rocket-3** [comment]
@yegor256, you probably know, what to do.

**Comment by yegor256** [comment]
@h1alexbel should be fixed now

**Comment by h1alexbel** [comment]
@yegor256 thanks!
