### ISSUE TITLE
Pull requests instead of write access

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/0pdd#5]
It would be better, I think, if the bot made PRs instead of asking for write permissions.

Moreover, it could scan the root folder of the repo for ``.rultor.yml``, check if it has commandment rights and if so, it should ask rultor to merge the pr. This way also the build is run and it assures that no mistake was made while removing puzzles. 

I think the integration with rultor is quite elegant. And if there i no rultor in the project, I still think people would rather check what the bot changed before merging. Since the bot does not run a build, it would be risky to just merge changes directly.

**Comment by yegor256** [comment]
@amihaiemil looks like I made a mistake in README. We don't really need write-access permissions, since @0pdd bot only submits issues and closes them.

**Comment by yegor256** [comment]
@amihaiemil see aad3155

**Comment by amihaiemil** [comment]
@yegor256 sure, cool ^^
