### ISSUE TITLE
codecov action is failed

### ISSUE THREAD

**Issue by pnatashap** [yegor256/0pdd#540]
Log:
`Run actions/setup-ruby@v1
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
Error: Version 2.[7](https://github.com/yegor256/0pdd/actions/runs/7509980227/job/20447795809#step:3:8) not found`

**Comment by pnatashap** [comment]
ruby is installed, but there is still a configuration error

**Comment by yegor256** [comment]
@pnatashap it's fixed in [4cc79b8](https://github.com/yegor256/0pdd/commit/4cc79b8a3c0d9f5858495dd60d0fa25e2fcf88c8), thanks for noticing!
