### ISSUE TITLE
0pdd web-service is broken 

### ISSUE THREAD

**Issue by nergal-perm** [yegor256/0pdd#567]
The 0pdd web-service stopped working recently, no issues are opened or closed based on changed puzzles in source files.  

Web page at https://www.0pdd.com/p?name=nergal-perm/java-decita shows the following:

Internal error at BUILD

Please help us improve our service and submit the following stacktrace to our issue tracker in GitHub: yegor256/0pdd

```
Input/output error @ io_fread - /tmp/0pdd-xml-cache/nergal-perm/java-decita
	/app/objects/storage/cached_storage.rb:32:in `read'
	/app/objects/storage/cached_storage.rb:32:in `load'
	/app/objects/storage/once_storage.rb:30:in `load'
	/app/objects/storage/safe_storage.rb:33:in `load'
	/app/objects/storage/upgraded_storage.rb:31:in `load'
	/app/objects/storage/sync_storage.rb:31:in `block in load'
	/app/objects/storage/sync_storage.rb:31:in `synchronize'
	/app/objects/storage/sync_storage.rb:31:in `load'
	/app/0pdd.rb:219:in `block in <top (required)>'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1706:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1706:in `block in compile!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1019:in `block (3 levels) in route!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1037:in `route_eval'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1019:in `block (2 levels) in route!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1068:in `block in process_route'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1066:in `catch'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1066:in `process_route'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1017:in `block in route!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1014:in `each'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1014:in `route!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1138:in `block in dispatch!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `catch'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `invoke'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1133:in `dispatch!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:949:in `block in call!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `catch'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `invoke'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:949:in `call!'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:938:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.8/lib/rack/deflater.rb:44:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-3.0.6/lib/rack/protection/xss_header.rb:20:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-3.0.6/lib/rack/protection/path_traversal.rb:18:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-3.0.6/lib/rack/protection/json_csrf.rb:28:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-3.0.6/lib/rack/protection/base.rb:53:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-3.0.6/lib/rack/protection/base.rb:53:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-protection-3.0.6/lib/rack/protection/frame_options.rb:33:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.8/lib/rack/logger.rb:17:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.8/lib/rack/common_logger.rb:38:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:261:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:254:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.8/lib/rack/head.rb:12:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.8/lib/rack/method_override.rb:24:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:219:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:2018:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1576:in `block in call'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1792:in `synchronize'
	/app/vendor/bundle/ruby/3.1.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1576:in `call'
	/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.8/lib/rack/handler/webrick.rb:95:in `service'
	/app/vendor/bundle/ruby/3.1.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:140:in `service'
	/app/vendor/bundle/ruby/3.1.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:96:in `run'
	/app/vendor/bundle/ruby/3.1.0/gems/webrick-1.8.1/lib/webrick/server.rb:310:in `block in start_thread'
```

**Comment by pnatashap** [comment]
Serivce is fine, your project file is broken for some reason
https://www.0pdd.com/xml?name=nergal-perm/java-decita 
`error on line 13 at column 8: Opening and ending tag mismatch: link line 12 and head`

**Comment by nergal-perm** [comment]
OK, is there some info on what should I (or anyone else) do to fix that project file? Do you have any clue on why did it broke? Where should I look to investigate this issue further?

**Comment by nergal-perm** [comment]
Does it mean that there's an XML-file for my project somewhere on a 0pdd server, and that XML-file was corrupted by writing HTML with an error description into it?

**Comment by pnatashap** [comment]
Html has less restrictions and not closed tags is not a problem. 
@yegor256 can you check what's wrong with the file?

**Comment by pnatashap** [comment]
Something happens after puzzle closing - last commit with one message about closing and after that the error

https://github.com/nergal-perm/java-decita/commit/d98cacde5c8677978823acfbfc2d51a6fadb99a5

**Comment by yegor256** [comment]
@pnatashap @nergal-perm the error is pretty weird: `File.exist?()` says `TRUE` and then `File.read()` raises an exception. This most probably means some low-level disk failure. Let's try to re-deploy, so that the entire cache is cleaned up.

**Comment by nergal-perm** [comment]
> @pnatashap @nergal-perm the error is pretty weird: `File.exist?()` says `TRUE` and then `File.read()` raises an exception. This most probably means some low-level disk failure. Let's try to re-deploy, so that the entire cache is cleaned up.

It seems that the broken file is just a symptom. The root problem appeared some time earlier, I suppose. Looks like the method that writes some data to a file expect the data to always be valid XML and just writes whatever came in. But earlier (deeper in the stack) the exception was raised and its text propagated until the file write moment. Could it be something like that?

**Comment by yegor256** [comment]
@pnatashap I also can't understand why it doesn't deploy now (some error with the `rackup`), maybe know how to fix?

**Comment by pnatashap** [comment]
@yegor256 looks like https://github.com/yegor256/0pdd/blob/master/Gemfile.lock#L272 should be '2.3.17'

**Comment by yegor256** [comment]
@rultor release, tag is `0.31.10`

**Comment by yegor256** [comment]
@pnatashap this was something else :(

**Comment by pnatashap** [comment]
@yegor256 you add app.json but https://github.com/pnatashap/0pdd/blob/master/CHECKS is still used and caused the error 
`Deprecated: Usage of the CHECKS file is deprecated in favor of healthchecks in app.jsonK
remote:  !     Please move your healthchecks to app.json.K
...
remote: 1G-----> Executing 3 healthchecks                                                        K
remote: 1G       Running healthcheck name='check-1' delay=0 path='/' retries=2 timeout=5 type='path'K
remote: 1G       Running healthcheck name='check-2' delay=0 path='/p?name=yegor256/0pdd' retries=2 timeout=5 type='path'K
remote: 1G       Running healthcheck name='port listening check' attempts=3 port=5000 retries=2 timeout=5 type='listening' wait=5K
remote: 1m31m !     0m0mFailure in name='check-1': Get "http://172.17.0.16:5000/": dial tcp 172.17.0.16:5000: connect: connection refusedK
remote: 1Gadf753485fea36abed0c915f592c651ce18e779484ef2dd724c8c1b859175676K
remote:  !     Could not start due to 2 failed checks (web.1)K`

**Comment by yegor256** [comment]
@rultor release, tag is `0.31.10`

**Comment by yegor256** [comment]
@rultor release, tag is `0.31.10`

**Comment by pnatashap** [comment]
@yegor256 please merge https://github.com/yegor256/0pdd/pull/571 first

**Comment by yegor256** [comment]
@rultor release, tag is `0.31.10`

**Comment by nergal-perm** [comment]
@yegor256 , @pnatashap , it helped, thanks. 

I suppose the issue can be closed.

**Comment by yegor256** [comment]
@nergal-perm ok, thanks, closing
