### ISSUE TITLE
reply to GitHub comments, if they happen

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#59]

**Comment by yegor256** [comment]
@0pdd hello

**Comment by yegor256** [comment]
@0pdd hey

**Comment by yegor256** [comment]
@0pdd hey

**Comment by 0pdd** [comment]
I see you're talking about me, but I can't reply, I'm not a chat bot

**Comment by yegor256** [comment]
@rultor release, tag is `0.14`

**Comment by 0pdd** [comment]
I see you're talking about me, but I can't reply, I'm not a chat bot

**Comment by 0pdd** [comment]
I see you're talking about me, but I can't reply, I'm not a chat bot.

**Comment by 0pdd** [comment]
I see you're talking about me, but I can't reply, I'm not a chat bot.

**Comment by 0pdd** [comment]
I see you're talking about me, but I can't reply, I'm not a chat bot.

**Comment by 0pdd** [comment]
I see you're talking about me, but I can't reply, I'm not a chat bot.

**Comment by 0pdd** [comment]
I see you're talking about me, but I can't reply, I'm not a chat bot.

**Comment by 0pdd** [comment]
I see you're talking about me, but I can't reply, I'm not a chat bot.

**Comment by 0pdd** [comment]
I see you're talking about me, but I can't reply, I'm not a chat bot.

**Comment by 0pdd** [comment]
I see you're talking about me, but I can't reply, I'm not a chat bot.

**Comment by 0pdd** [comment]
I see you're talking about me, but I can't reply, I'm not a chat bot.

**Comment by 0pdd** [comment]
I see you're talking about me, but I can't reply, I'm not a chat bot.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#59` was not in scope
