### ISSUE TITLE
Doesn't see hidden files

### ISSUE THREAD

**Issue by pchmielowski** [yegor256/0pdd#62]
I have file `.zshrc` in repo. 0pdd doesn't see `@todo` marker in it.
I've made a copy called `zshrc` - with this file, it works correctly.

(To make it clear - by "hidden" I mean files starting with the dot)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@pchmielowski interesting, I will take a look now, cross posted it here: https://github.com/yegor256/pdd/issues/61

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.1`

**Comment by yegor256** [comment]
@pchmielowski should be fine now, please check

**Comment by pchmielowski** [comment]
Now it is OK. Thanks!

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#62` was not in scope

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#62` was not in scope
