### ISSUE TITLE
safe_tickets.rb:27-29: Would be great to make sure the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/0pdd#64]
The puzzle `40-679dfbe3` in [`objects/safe_tickets.rb`](https://github.com/yegor256/0pdd/blob/master/objects/safe_tickets.rb) (lines 27-29) has to be resolved: Would be great to make sure the exceptions that we swallow here are also emailed to the admin, in order not to be lost. Let's do it as soon as possible.

The puzzle was created by Yegor Bugayenko on 06-Apr-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
Hey, I'll fix it

**Comment by 0pdd** [comment]
The puzzle `40-679dfbe3` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#64` was not in scope

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
