### ISSUE TITLE
0pdd does not create issue...

### ISSUE THREAD

**Issue by DronMDF** [yegor256/0pdd#67]
https://github.com/DronMDF/goost/blob/master/kuznyechik/Imit.cpp

Where I was wrong?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by DronMDF** [comment]
Yes, this is my mistake. One of the 4 comments turned out to be an incorrect format and 0pdd fell on an exception.

It's strange that three correct todo did not appear in the tracker...

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#67` was not in scope
