### ISSUE TITLE
An error in one of the comments results in ignoring all the others.

### ISSUE THREAD

**Issue by DronMDF** [yegor256/0pdd#68]
In case of violation of formatting 0pdd falls by exception.
This happens even if most of the comments are correctly written.

My merge [commit](https://github.com/DronMDF/goost/commit/abe40615b7362843b1f8c1ba6dbe12d457048b6d) for example.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF yes, this is how it's supposed to be. If [pdd](https://github.com/yegor256/pdd) can't parse your _entire_ code base, it will crash and we can't update your puzzles.
