### ISSUE TITLE
notification processing is messy

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#69]

**Comment by yegor256** [comment]
@0pdd how are you?

**Comment by yegor256** [comment]
@0pdd are you there

dude?

**Comment by 0pdd** [comment]
> @0pdd are you there dude?

I see you're talking about me; I can't reply, I'm not a chat bot.

**Comment by yegor256** [comment]
@0pdd talk to me

**Comment by 0pdd** [comment]
> @0pdd talk to me

I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by yegor256** [comment]
I'm just talking, @0pdd

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.4`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#69` was not in scope
