### ISSUE TITLE
post comments to commits when new puzzles found

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#74]
Let's post commit comments if/when new puzzles are found or old ones were closed.

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#74` was not in scope
