### ISSUE TITLE
0pdd.rb:91-93: Would be better to store these two...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/0pdd#77]
The puzzle `76-925a3c27` in [`0pdd.rb`](https://github.com/yegor256/0pdd/blob/master/0pdd.rb) (lines 91-93) has to be resolved: Would be better to store these two guys somewhere in configuration and re-use on every click. At the moment we are making too many unnecessary calls to the operating system.

The puzzle was created by 0pdd on 17-Apr-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `76-925a3c27` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#77` was not in scope

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
