### ISSUE TITLE
let's accept both JSON and urlencoded hooks

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#88]
Let's accept both `application/json` and `application/x-www-form-urlencoded` from GitHub

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#88` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+2520](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#88` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+2550](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.21`
