### ISSUE TITLE
Can 0pdd create puzzles from golang code ?

### ISSUE THREAD

**Issue by Slach** [yegor256/0pdd#89]
@yegor256 pls see https://github.com/Slach/test_tasks/commit/ee5593bcd9712f555c506a3334b417c6ff3ec346
what i need improve in my code for use PDD in my development workflow?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@Slach you must format puzzles as explained here: https://github.com/yegor256/pdd#how-to-run

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#89` was not in scope
