### ISSUE TITLE
single line comment format for puzzles ?

### ISSUE THREAD

**Issue by Slach** [yegor256/0pdd#92]
@yegor256  would pdd parse single line comment?
like this
```
/** @todo #<ticket number>:XXm/DEV puzzle explain */
```

i submit some code changes here https://github.com/Slach/test_tasks/pull/3/commits/f52c2ed70dd0e53f866cec081857c66c6497ec2d
but pdd have a zero reaction

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@Slach the format looks correct. Did you try to parse it using [pdd](https://github.com/yegor256/pdd) command line tool?

**Comment by Slach** [comment]
yep, i figure out in .pdd format and add allowed duplicates
thanks for your feedback

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#92` was not in scope
