### ISSUE TITLE
pdd closing active puzzle issues...

### ISSUE THREAD

**Issue by DronMDF** [yegor256/0pdd#94]
dronmdf/2out#58 is closed.

But puzzle text still in source code. https://github.com/DronMDF/2out/blob/master/src/TextReport.cpp#L41

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by DronMDF** [comment]
May be this can help...
https://github.com/DronMDF/2out/commit/dee2d7c09d5a90e82ba10c3a30df1a4e36b0228b
0pdd write some information in comments... and ignore my puzzles.

**Comment by DronMDF** [comment]
Local pdd 0.17.8 work fine.

**Comment by DronMDF** [comment]
Local pdd 0.17.8 work fine.

**Comment by yegor256** [comment]
@DronMDF it was a bug on our side, already fixed. Can you confirm? Works now?

**Comment by DronMDF** [comment]
@yegor256 What caused the problem?
In last week I haven't lost my puzzles.

**Comment by DronMDF** [comment]
@yegor256  Problem cause again.

Puzzle https://github.com/DronMDF/2out/issues/261 still in code, but closed.

**Comment by yegor256** [comment]
@DronMDF looks weird, I'm investigating...

**Comment by yegor256** [comment]
@DronMDF is it still a problem or you can close the issue?

**Comment by DronMDF** [comment]
Recently I have not observed this.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#94` was not in scope
