### ISSUE TITLE
bot not creating issues

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/0pdd#96]
I have some @todo comments as per styling documentation in my code but no issues have been created... will this only occur for new commits?

https://github.com/ashtonhogan/elegantdb

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@ashtonhogan did you configure the webhook?

**Comment by yegor256** [comment]
@ashtonhogan see the comments 0pdd posts to your commits, for example: https://github.com/ashtonhogan/elegantdb/commit/ec6f41f629d0688f7e6f4e6f05f0cd33d87e13b1

**Comment by ashtonhogan** [comment]
It's cool, this is old news, I completely forgot about `elegantdb` to be honest
