### ISSUE TITLE
Is it possible to configure 0pdd bot to fetch puzzles from all branches (not just master)?

### ISSUE THREAD

**Issue by driver733** [yegor256/0pdd#97]
As of now @0pdd creates issues only from the puzzles found in the master branch. I would like it to create issues from all branches.
This would be useful in the following scenario:

1. Create a puzzle in code.
2. Commit and push it to a new branch.
3. Write the code that closes the created issue.
4. Remove the puzzle from code.
5. Commit the code (the issue will be closed by the bot).
6. Merge the created branch with the master branch.
7. Delete the created branch.

How can I make @0pdd work in the described fashion?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@driver733 well, this is against the workflow we're trying to enforce with 0pdd. You must only do what `master` tells you to do.

**Comment by driver733** [comment]
@yegor256 Alright

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/0pdd#97` was not in scope
