### ISSUE TITLE
git checkout master doesn't work

### ISSUE THREAD

**Issue by yegor256** [yegor256/0pdd#98]
```
+ set -e
+ set -o pipefail
+ cd /tmp/0pdd20170625-4-1onwpfh/xxx/xxx
+ git reset --hard --quiet
+ git clean --force -d
+ git fetch --quiet
+ git checkout master
Warning: you are leaving 1 commit behind, not connected to
any of your branches:

  14f1b47 configured 0pdd

If you want to keep it by creating a new branch, this may be a good time
to do so with:

 git branch  14f1b47

Switched to branch 'master'
+ git rebase --abort
+ git rebase --strategy-option=theirs origin/master
fatal: Could not parse object '251000d38852773d78985b00a29c6685808bd0ca^'
Unknown exit code (128) from command: git-merge-recursive 251000d38852773d78985b00a29c6685808bd0ca^ -- HEAD 251000d38852773d78985b00a29c6685808bd0ca

Your branch and 'origin/master' have diverged,
and have 1 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
First, rewinding head to replay your work on top of it...
```

**Comment by 0crat** [comment]
Job [#98](https://github.com/yegor256/0pdd/issues/98) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8435](https://www.0crat.com/u/yegor256)

**Comment by SilasReinagel** [comment]
@yegor256 This bug is missing reproduction steps and bug incident context. All bug reports should have at least one of those. 

Where did this bug occur? What other things happened on the box that the error occurred?

**Comment by yegor256** [comment]
@SilasReinagel it's impossible to say. It happened half a year ago. Most likely this issue is no longer with us.

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/0pdd/issues/98#issuecomment-380542161))

@yegor256 Job `gh:yegor256/0pdd#98` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#98](https://github.com/yegor256/0pdd/issues/98) is now out of scope
